"""Roll stats according to Method IV

(AD&D DMG, p.11) A player will generate 12 sets of character ability scores.
A set is generated by rolling 3d6 six times. The best 3 of these sets are
retained and used for character creation by that player. The scores within
a retained set may be arranged as desired by the player when a character is
created.
"""

import random

d6 = lambda: random.randint(1, 6)
stat = lambda: d6() + d6() + d6()

rolls = list()
for i in range(1, 13):
    foo = [stat() for x in range(6)]
    rolls.append((sum(foo), foo))
rolls.sort(reverse=True)
for total, scores in rolls:
    print('{}: {} {}'.format(total, ' '.join('{:2}'.format(x) for x in scores), '*' * sum(x >= 15 for x in scores)))
