#!/usr/bin/env python3
"""Roll stats according to Method IV.

(AD&D DMG, p.11) A player will generate 12 sets of character ability scores.
A set is generated by rolling 3d6 six times. The best 3 of these sets are
retained and used for character creation by that player. The scores within
a retained set may be arranged as desired by the player when a character is
created.

Author: Norman J. Harman Jr. <njharman@gmail.com>
Copyright: Released into Public Domain Jan 2021.
Website: http://trollandflame.blogspot.com/
"""

import random

names = ('Str', 'Int', 'Wis', 'Dex', 'Con', 'Cha')
d6 = lambda: random.randint(1, 6)
roll = lambda: d6() + d6() + d6()

rolls = list()
for i in range(1, 13):
    foo = [roll() for x in range(6)]
    rolls.append((sum(foo), foo))
rolls.sort(reverse=True)
print('total: scores  * = score >= 15')
for total, scores in rolls:
    abilities = '  '.join(f'{x} :{y:2}' for x, y in zip(names, scores))
    good = '*' * sum(x >= 15 for x in scores)
    print(f'{total}: {abilities} {good}')
