#!/usr/bin/env python
# meant to be piped to from vim

import re
import sys

NUMBA = re.compile(r'(\d+)\s*[xg]p')

total = 0
unit = None
for line in sys.stdin.readlines():
    if unit is None:
        if 'gp' in line:
            unit = 'gp'
        elif 'xp' in line:
            unit = 'xp'
    print line.rstrip()
    match = NUMBA.search(line)
    if match:
        total += int(match.group(1))
print '-----------\n%s%s or six %s%s shares' % (total, unit, total/6, unit)
#print '-----------\n%s%s or seven %s%s shares' % (total, unit, total/7, unit)
