#!/usr/bin/env python2
# meant to be piped to from vim

import re
import sys

NUMBA = re.compile(r'([\d,]+)')

total = 0
unit = None
for line in sys.stdin.readlines():
    print line.rstrip()
    match = NUMBA.search(line)
    if match:
        total += int(match.group(1).replace(',', ''))
print total
