'''
Various legal bits for Open Game License, TradeMarks.
'''

def merge_ogl(*args):
    '''Combine, removing dupes and alpha sort one or more OGL section 15 copyrights.'''
    merged = set()
    for section in args:
        for line in section:
            merged.add(line)
    return sorted(merged)


aecTM = (
    '''Labyrinth Lord(TM), Advanced Labyrinth Lord(TM) and Goblinoid Games(TM) are trademarks of Daniel Proctor.''',
    )

ogl = (
    '''OPEN GAME LICENSE Version 1.0a''',
    '''The following text is the property of Wizards of the Coast, Inc. and is Copyright 2000 Wizards of the Coast, Inc ("Wizards").  All Rights Reserved.''',
    '''1. Definitions: (a)"Contributors" means the copyright and/or trademark owners who have contributed Open Game Content; (b)"Derivative Material" means copyrighted material including derivative works and translations (including into other computer languages), potation, modification, correction, addition, extension, upgrade, improvement, compilation, abridgment or other form in which an existing work may be recast, transformed or adapted; (c) "Distribute" means to reproduce, license, rent, lease, sell, broadcast, publicly display, transmit or otherwise distribute; (d)"Open Game Content" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identified as Open Game Content by the Contributor, and means any work covered by this License, including translations and derivative works under copyright law, but specifically excludes Product Identity. (e) "Product Identity" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; and any other trademark or registered trademark clearly identified as Product identity by the owner of the Product Identity, and which specifically excludes the Open Game Content; (f) "Trademark" means the logos, names, mark, sign, motto, designs that are used by a Contributor to identify itself or its products or the associated products contributed to the Open Game License by the Contributor (g) "Use", "Used" or "Using" means to use, Distribute, copy, edit, format, modify, translate and otherwise create Derivative Material of Open Game Content. (h) "You" or "Your" means the licensee in terms of this agreement.''',
    '''2. The License: This License applies to any Open Game Content that contains a notice indicating that the Open Game Content may only be Used under and in terms of this License. You must affix such a notice to any Open Game Content that you Use. No terms may be added to or subtracted from this License except as described by the License itself.  No other terms or conditions may be applied to any Open Game Content distributed using this License.''',
    '''3. Offer and Acceptance: By Using the Open Game Content You indicate Your acceptance of the terms of this License.''',
    '''4. Grant and Consideration: In consideration for agreeing to use this License, the Contributors grant You a perpetual, worldwide, royalty-free, non-exclusive license with the exact terms of this License to Use, the Open Game Content.''',
    '''5. Representation of Authority to Contribute: If You are contributing original material as Open Game Content, You represent that Your Contributions are Your original creation and/or You have sufficient rights to grant the rights conveyed by this License.''',
    '''6. Notice of License Copyright: You must update the COPYRIGHT NOTICE portion of this License to include the exact text of the COPYRIGHT NOTICE of any Open Game Content You are copying, modifying or distributing, and You must add the title, the copyright date, and the copyright holder's name to the COPYRIGHT NOTICE of any original Open Game Content you Distribute.''',
    '''7. Use of Product Identity: You agree not to Use any Product Identity, including as an indication as to compatibility, except as expressly licensed in another, independent Agreement with the owner of each element of that Product Identity. You agree not to indicate compatibility or co-adaptability with any Trademark or Registered Trademark in conjunction with a work containing Open Game Content except as expressly licensed in another, independent Agreement with the owner of such Trademark or Registered Trademark.  The use of any Product Identity in Open Game Content does not constitute a challenge to the ownership of that Product Identity. The owner of any Product Identity used in Open Game Content shall retain all rights, title and interest in and to that Product Identity.''',
    '''8. Identification: If you distribute Open Game Content You must clearly indicate which portions of the work that you are distributing are Open Game Content.''',
    '''9. Updating the License: Wizards or its designated Agents may publish updated versions of this License. You may use any Authorized version of this License to copy, modify and distribute any Open Game Content originally distributed under any version of this License.''',
    '''10. Copy of this License: You MUST include a copy of this License with every copy of the Open Game Content You Distribute.''',
    '''11. Use of Contributor Credits: You may not market or advertise the Open Game Content using the name of any Contributor unless You have written permission from the Contributor to do so.''',
    '''12. Inability to Comply: If it is impossible for You to comply with any of the terms of this License with respect to some or all of the Open Game Content due to statute, judicial order, or governmental regulation then You may not Use any Open Game Material so affected.''',
    '''13. Termination: This License will terminate automatically if You fail to comply with all terms herein and fail to cure such breach within 30 days of becoming aware of the breach.  All sublicenses shall survive the termination of this License.''',
    '''14. Reformation: If any provision of this License is held to be unenforceable, such provision shall be reformed only to the extent necessary to make it enforceable.''',
    '''15. COPYRIGHT NOTICE''',
    '''Open Game License v 1.0 Copyright 2000, Wizards of the Coast, Inc.''',
    '''Open Game License v 1.0a Copyright 2000, Wizards of the Coast, Inc.''',
    '''System Reference Document Copyright 2000, Wizards of the Coast, Inc.; Authors Jonathon Tweet, Monte Cook, Skip Williams, based on original material by E. Gary Gygax and Dave Arneson.''',
    '''System Reference Document Copyright 2000-2003, Wizards of the Coast, Inc.; Authors Jonathan Tweet, Monte Cook, Skip Williams, Rich Baker, Andy Collins, David Noonan, Rich Redman, Bruce R. Cordell, John D. Rateliff, Thomas Reid, James Wyatt, based on original material by E. Gary Gygax and Dave Arneson.''',
    )

# ogl section 15
swc15 = (
    '''Swords & Wizardry Core Rules, Copyright 2008, Matthew J. Finch.''',
    '''Swords & Wizardry Complete Rules, Copyright 2010, Matthew J. Finch.''',
    )

# ogl section 15
aec15 = (
    '''Modern System Reference Document Copyright 2002-2004, Wizards of the Coast, Inc.; Authors Bill Slavicsek, Jeff Grubb, Rich Redman, Charles Ryan, Eric Cagle, David Noonan, Stan!, Christopher Perkins, Rodney Thompson, and JD Wiker, based on material by Jonathan Tweet, Monte Cook, Skip Williams, Richard Baker, Peter Adkison, Bruce R. Cordell, John Tynes, Andy Collins, and JD Wiker.''',
    '''Aerial Servant from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Axe Beak from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Beetle, Giant Boring from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Beetle, Giant Rhinoceros from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Brownie from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Castles & Crusades: Players Handbook, Copyright 2004, Troll Lord Games; Authors Davis Chenault and Mac Golden.''',
    '''Cave Cricket from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Crab, Monstrous from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Crayfish, Monstrous from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Darwin's World Copyright 2002, RPGObjects; Authors Dominic Covey and Chris Davis.''',
    '''Demon: Juiblex "The Faceless Lord" (Demon Lord) from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Demon: Orcus (Demon Prince of Undead) from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Devil: Amon (Duke of Hell) from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Devil: Bael (Duke of Hell) from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Devil: Geryon (Arch-Devil) from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Ear Seeker from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Erica Balsley, based on original material by Gary Gygax.''',
    '''Eel, Electric from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene.''',
    '''Eye of the Deep from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Floating Eye from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Fly, Giant from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Frog, Monstrous from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Frog, Monstrous Killer from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Frog, Monstrous Poisonous from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Gas Spore from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Golem, Wood from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Patrick Lawinger.''',
    '''Gorbel from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Andrew Key.''',
    '''Groaning Spirit from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Hippocampus from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Erica Balsey, based on original material by Gary Gygax.''',
    '''Jackalwere from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene based, on original material by Gary Gygax.''',
    '''Kamadan from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Nick Louth.''',
    '''Leprechaun from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene based on original material by Gary Gygax.''',
    '''Lurker Above from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Mutant Future(TM) Copyright 2008, Daniel Proctor and Ryan Denison. Authors Daniel Proctor and Ryan Denison.''',
    '''Piercer from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Rot Grub from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Slithering Tracker from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Slug, Giant from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Strangle Weed from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Tick, Giant from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Trapper from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Turtle, Giant Snapping from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Green, based on original material by Gary Gygax.''',
    '''Wind Walker from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Yeti from the Tome of Horrors, copyright 2002, Necromancer Games, Inc.; Author Scott Green, based on original material by Gary Gygax.''',
    '''Labyrinth Lord(TM) Copyright 2007-2009, Daniel Proctor. Author Daniel Proctor.''',
    '''Advanced Edition Companion, Copyright 2009-2010, Daniel Proctor. Author Daniel Proctor.''',
    )

# ogl section 15
tt15 = (
    '''Theorems & Thaumaturgy Copyright 2012 Gavin Norman. Author Gavin Norman.''',
    )

# ogl section 15 from BMII
bm15 = (
    '''Modern System Reference Document Copyright 2002-2004, Wizards of the Coast, Inc.; Authors Bill Slavicsek, Jeff Grubb, Rich Redman, Charles Ryan, Eric Cagle, David Noonan, Stan!, Christopher Perkins, Rodney Thompson, and JD Wiker, based on material by Jonathan Tweet, Monte Cook, Skip Williams, Richard Baker, Peter Adkison, Bruce R. Cordell, John Tynes, Andy Collins, and JD Wiker.''',
    '''Advanced Edition Companion, Copyright 2009-2010, Daniel Proctor. Author Daniel Proctor.''',
    '''Aerial Servant from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Amber Jelly from A Hamsterish Hoard of Dungeons and Dragons 2008-2001; Author Erin "taichara" Bisson.''',
    '''Amphisbaena from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Armbands of Healing by James Bobb from Knockspell Magazine Issue 4, Copyright 2009, Mathew J. Finch.''',
    '''Axe Beak from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Barrow Wight from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene.''',
    '''Battered Top Hat by Chris D., Knockspell Magazine Issue 2, Copyright 2009, Mathew J. Finch.''',
    '''Beetle, Giant Boring from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Beetle, Giant Rhinoceros from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Black Skeleton from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Authors Scott Greene and Bill Webb.''',
    '''Book of Templates: Deluxe Edition Copyright 2003, Silverthorne Games; Authors Ian Johnston and Chris S. Sims.''',
    '''Brass Jackal from A Hamsterish Hoard of Dungeons and Dragons, 2008-2001; Author Erin "taichara" Bisson.''',
    '''Brown Mold from the Swords & Wizardry Monster Book: Oe, Copyright 2008, Matthew J. Finch.''',
    '''Brown Pudding from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Brownie from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Caryatid Column from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Jean Wells.''',
    '''Castles & Crusades: Players Handbook, Copyright 2004, Troll Lord Games; Authors Davis Chenault and Mac Golden.''',
    '''Castles & Crusades: Players Handbook, 2nd Printing, Copyright 2006, Troll Lord Games; Authors Davis Chenault and Mac Golden.''',
    '''Castles & Crusades: Monsters & Treasure, Copyright 2005, Troll Lord Games; Authors Robert Doyle and Stephen Chenault.''',
    '''Cave Cricket from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Cave Fisher from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Lawrence Schick.''',
    '''Cave Moray from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Coffer Corpse from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Simon Eaton.''',
    '''Corpse Candle from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene.''',
    '''Crab, Monstrous from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Crayfish, Monstrous from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Crypt Shade from Stonehell Dungeon: Down Night-Haunted Halls, Copyright 2009, Michael Curtis; Author Michael Curtis.''',
    '''Crypt Thing from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Roger Musson.''',
    '''Darwin's World Copyright 2002, RPG Objects; Authors Dominic Covey and Chris Davis.''',
    '''Demon: Juiblex "The Faceless Lord" (Demon Lord) from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Demon: Orcus (Demon Prince of Undead) from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Demonic Knight from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene.''',
    '''Devil: Amon (Duke of Hell) from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Devil: Bael (Duke of Hell) from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Devil: Geryon (Arch-Devil) from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Ear Seeker from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Erica Balsley, based on original material by Gary Gygax.''',
    '''Eel, Electric from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene.''',
    '''Eye of the Deep from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Exploding Bones from the Swords & Wizardry Monster Book, Copyright 2008, Matthew J. Finch; Author Skathros.''',
    '''Fire Crab from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene.''',
    '''Flagstone Golem from the Tome of Horrors III, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene.''',
    '''Floating Eye from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Fly, Giant from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Fossil Skeleton from the Swords & Wizardry Monster Book, Copyright 2008, Matthew J. Finch; Author Matt Finch.''',
    '''Four-Armed Gargoyle from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; No Author listed.''',
    '''Frog, Monstrous from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Frog, Monstrous Killer from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Frog, Monstrous Poisonous from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Froghemoth from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Gas Spore from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Giant Ant Exoskeleton from the Swords & Wizardry Monster Book: Oe, Copyright 2008, Matthew J. Finch.''',
    '''Golem, Wood from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Patrick Lawinger.''',
    '''Gorbel from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Andrew Key.''',
    '''Groaning Spirit from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Grognardia, Copyright 2008-2011, James Maliszewski.''',
    '''Hippocampus from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Erica Balsey, based on original material by Gary Gygax.''',
    '''Horn of Battle in Artifacts, Adjuncts, and Oddments: Fell Magick Items of Duvan'Ku by James Edward Raggi IV in Fight On! Issue 4, 2009; Publisher and Editor Ignatius Umlaut.''',
    '''Huecuva from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Underworld Oracle.''',
    '''Jackalwere from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene based, on original material by Gary Gygax.''',
    '''Kamadan from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Nick Louth.''',
    '''Knockspell Magazine Issue #2, Copyright 2009, Matthew J. Finch.''',
    '''Knockspell Magazine Issue #3, Copyright 2009, Matthew J. Finch.''',
    '''Labyrinth Lord(TM) Copyright 2007-2009, Daniel Proctor. Author Daniel Proctor.''',
    '''Lava Weird from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene, based on original material by Nigel Morgan.''',
    '''Lead Skeleton from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Authors Patrick Lawinger and Scott Greene.''',
    '''Leprechaun from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene based on original material by Gary Gygax.''',
    '''Lurker Above from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Maggog Gargoyle from the Swords & Wizardry Monster Book: Oe, Copyright 2008, Matthew J. Finch; Author Old Crawler.''',
    '''Margoyle from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Mongrelman from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Mutant Future(TM) Copyright 2008, Daniel Proctor and Ryan Denison. Authors Daniel Proctor and Ryan Denison.''',
    '''Neb'Enakhet from Knockspell Magazine Issue 3, Copyright 2009, Mathew J. Finch. Author Andrew Trent.''',
    '''Original Spell Name Compendium Copyright 2002 Clark Peterson; based on NPC-named spells from the Player's Handbook that were renamed in the System Reference Document. The Compendium can be found on the legal page of www.necromancergames.com.''',
    '''Phantom from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Harold Johnson and Tom Moldvay.''',
    '''Piercer from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Poltergeist from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Lewis Pulsipher.''',
    '''Purple Moss from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene, based on original material by Jean Wells.''',
    '''Pyre Zombie from the Swords and Wizardry Monster Book, Copyright 2008, Mathew J. Finch, based on original material by Scott Casper.''',
    '''Random Pits and Occupants by Mike Davison, Knockspell Magazine Issue 2, Copyright 2009, Mathew J. Finch.''',
    '''Rot Grub from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene and Clark Peterson, based on original material by Gary Gygax.''',
    '''Rot Pudding, Knockspell Issue #6, Copyright 2001; Author Matt Finch.''',
    '''Sandling from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Lawrence Schick.''',
    '''Skeleton Warrior from the Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Author Scott Greene.''',
    '''Slithering Tracker from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Slug, Giant from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Stonehell Dungeon: Down Night-Haunted Halls, Copyright 2009, Michael Curtis; Author Michael Curtis.''',
    '''Strangle Weed from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Swords & Wizardry Core Rules, Copyright 2008, Matthew J. Finch.''',
    '''Swords & Wizardry Complete Rulebook, Copyright 2010, Matthew J. Finch.''',
    '''Swords & Wizardry Monster Book: Oe, Copyright 2008, Matthew J. Finch.''',
    '''Tick, Giant from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Tomb of the Iron God, Copyright 2008, Matthew J. Finch.''',
    '''Tome of Horrors I, Copyright 2002, Necromancer Games, Inc.; Authors Scott Greene, with Clark Peterson, Erica Balsley, Kevin Basse, Casey Christofferson, Lance Hawvermale, Travis Hawvermale, Patrick Lawringer, and Bill Webb.''',
    '''Tome of Horrors II, Copyright 2004, Necromancer Games, Inc.; Authors Scott Greene; Additional Authors: Erica Balsley, Kevin Basse, Casey Christofferson, Jim Collura, Meghan Greene, Lance Hawvermale, Travis Hawvermale, Bill Kenower, Patrick Lawinger, Nathan Paul, Clark Peterson, Bill Webb and Monte Cook.''',
    '''Tome of Horrors III, Copyright 2005, Necromancer Games, Inc.; Authors Scott Greene, with Casey Christofferson, Erica Balsley, Kevin Baase, Lance Hawvermale, Travis Hawvermale, Ian S. Johnston, Patrick Lawringer, Nathan Paul, Clark Peterson, Greg Ragland, Robert Schwalb and Bill Webb.''',
    '''Tome of Horrors Complete, Copyright 2011, Necromancer Games, Inc., published and distributed by Frog God Games; Authors Scott Greene and Erica Balsley. Lair encounter Authors John Stater, Jeff Harkness, Gary Schotter. Additional Authors Kevin Basse, Casey Christofferson, Jim Collura, Meghan Greene, Lance Hawvermale, Travis Hawvermale, Ian S. Johnston, Nill Kenower, Patrick Lawringer, Nathan Paul, Clark Peterson, Greg Ragland, Robert Schwalb, Greg A. Vaughan, Bill Webb.''',
    '''Trapper from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Turtle, Giant Snapping from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Green, based on original material by Gary Gygax.''',
    '''When is a Spell Book Much More than a Spell Book? by Brendan Falconer, Knockspell Magazine Issue 2, Copyright 2009, Mathew J. Finch.''',
    '''Wind Walker from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Greene, based on original material by Gary Gygax.''',
    '''Yeti from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Green, based on original material by Gary Gygax.''',
    '''Zombie, Juju from the Tome of Horrors, Copyright 2002, Necromancer Games, Inc.; Author Scott Green, based on original material by Gary Gygax.''',
    '''Barrowmaze, Copyright 2012, Greg Gillespie; Author Greg Gillespie.''',
    '''Barrowmaze II, Copyright 2012, Greg Gillespie; Author Greg Gillespie.''',
    )
