# "Known" names of entries, useful for finding parsing errors.

known = [
## LL Conversions
    '''Ghost''',
    '''Golem, Amber''',
    '''Golem, Bone''',
    '''Demon, Babau''',


## S&W Monstrosities
    '''Aaztar-Ghola''',
    '''Amphoron of Yothri, Juggernaut''',
    '''Amphoron of Yothri, Warrior''',
    '''Amphoron of Yothri, Worker''',
    '''Animated Carpet''',
    '''Animated Chair''',
    '''Ankheg''',
    '''Ape, Carnivorous''',
    '''Ape, Centaur''',
    '''Ape, Gorilla''',
    '''Archer Tree''',
    '''Artificers of Yothri''',
    '''Astral Moth''',
    '''Bat Monster''',
    '''Bear, Cave''',
    '''Bear, Polar''',
    '''Bee, Giant''',
    '''Beetle, Giant''',
    '''Beetle, Giant Huhu''',
    '''Birhaakaman''',
    '''Brainosaurian''',
    '''Brainstorm''',
    '''Cannibal Mole Men''',
    '''Carrion Fly''',
    '''Cattle''',
    '''Cave Eel''',
    '''Chalkeion''',
    '''Cloaker''',
    '''Corpse Tree''',
    '''Crab Man''',
#    '''Demon, Arauk (First-Category Demon)''',
#    '''Demon, Baalroch (Balor), (Sixth-Category Demon)''',
    '''Demon, Coral''',
    '''Demon, Darkswimmer''',
#    '''Demon, Glabrezu (Third-Category Demon)''',
#    '''Demon, Hezrou (Second-Category Demon)''',
#    '''Demon, Khavorr (Third-Category Demon)''',
#    '''Demon, Larvaxu (Second-Category Demon)''',
#    '''Demon, Marilith (Fifth-Category Demon)''',
#    '''Demon, Nalfeshnee (Fourth-Category Demon)''',
#    '''Demon-Prince of Carrion''',
#    '''Demon-Prince of Mists''',
#    '''Demon-Prince of THE UNDEAD''',
#    '''Demon-Princess of Dimensions''',
#    '''Demon, Shaavazi (Fourth-Category Demon)''',
    '''Demon-Stirge''',
    '''Demonvessel''',
#    '''Demon, Vrock (First-Category Demon)''',
    '''Demon-Wolf of Braazz''',
    '''Demon, Yildra''',
    '''Denizen of Leng''',
    '''Dergenue''',
    '''Dinosaur, Tyrannosaurus''',
    '''Dog, Guard''',
    '''Dog, War''',
    '''Doppleganger''',
    '''Dragon, Brass''',
    '''Dragon, Bronze''',
    '''Dragon, Copper''',
    '''Dragon, Silver''',
    '''Draug''',
    '''Drow''',
    '''Duergar''',
    '''Eternal Gladiator''',
    '''Exoskeleton, Giant Ant''',
    '''Exoskeleton, Giant Beetle''',
    '''Exoskeleton, Giant Crab''',
    '''Fal-Yoth''',
    '''Fledgling''',
    '''Flenser''',
    '''Flowerchild''',
    '''Flowershroud''',
    '''Flying Squirrel, Carnivorous''',
    '''Flytrap Shambler''',
    '''Foxtaur''',
    '''Frog, Zen''',
    '''Gallows Tree''',
    '''Ghost, Strangling''',
    '''Ghoul, Ao-Nyobo''',
    '''Ghoul, Crimson''',
    '''Giant, Daimyo''',
    '''Giant, Khmornian''',
    '''Glimmer''',
#    '''Goblin, Belfry (Vampiric)''',
#    '''Goblin, Oni-Aka (Asian Red Goblin)''',
#    '''Goblin, Oni-Kage (Asian Shadow Goblin)''',
#    '''Goblin, Oni-Yama (Asian Mountain Goblin)''',
    '''Goblin, Redcap''',
    '''Golem, Glass''',
    '''Green Brain''',
    '''Grey Ooze''',
    '''Growling Shadow''',
    '''Grue (Type 1)''',
    '''Grue (Type 2)''',
    '''Gwurrum''',
#    '''Hag, Mountain (Yama-Uba)''',
    '''Head-Stealer''',
    '''Hellcat''',
    '''Hellhound''',
    '''Homonculus''',
    '''Horse, Riding''',
    '''Horse, War''',
    '''Hound of Chronos''',
    '''Human, Bandits''',
    '''Human, Berserkers''',
    '''Inner Child''',
    '''Iounifier''',
    '''Jackalwere''',
    '''Jellyfish, Hypnotic''',
    '''Keeper of the Well''',
    '''Kheph, Elder''',
    '''Kheph, Mage''',
    '''Kheph, Priest''',
    '''Kheph, Warrior''',
    '''Khryll''',
    '''Kzaddich''',
    '''Lammasu''',
    '''Lichenthrope''',
    '''Linnorm''',
    '''Lizard, Samurai''',
    '''Lizard, Samurai Captain''',
    '''Lobster-Giant''',
    '''Lycanthrope, Wereweasel''',
    '''Mantis, Giant Praying''',
    '''Mechanism, Bronze Cobra''',
    '''Mechanism, Bronze Cobra''',
    '''Mechanism, Cavalier''',
    '''Mechanism, Clockwork Cavalier''',
    '''Mechanism, Giant''',
    '''Mechanism, Giant Robot''',
    '''Mechanism, Iron Cobra''',
    '''Mechanism, Iron Cobra''',
    '''Mephit, Brimstone''',
    '''Mephit, Fire''',
    '''Midden Monster''',
    '''Minor Major''',
    '''Mist-Men''',
    '''Mohrg''',
    '''Mushroom-Man''',
    '''Neomorphic Twin''',
    '''Night Hag''',
    '''Normal''',
    '''Normal Giant''',
    '''Ogre, Swamp''',
    '''Ophidian''',
    '''Ophidian, Sterile''',
    '''Panther''',
    '''Pet or Wild''',
    '''Portal Camel''',
    '''Pseudo-Dragon''',
    '''Pudding, Rot''',
    '''Quadricorn''',
    '''Quarn''',
    '''Rat, Desongnol''',
    '''Rat, Huge''',
    '''Rat, Lab''',
    '''Raven, Zombie''',
    '''Ray, Giant Manta''',
    '''Ray, Sting''',
    '''Razor Wing''',
    '''Redwraith''',
    '''Remorhaz''',
    '''Rhinoceros, Wooly''',
    '''Rock Weasel, Giant''',
    '''Rusalka''',
    '''Samurai Captain''',
    '''Sand Screamer''',
    '''Sea Horse, Giant''',
    '''Shark, Giant''',
    '''Shark, Large''',
    '''Shark, Large''',
    '''Shark, Medium''',
    '''Shark, Medium''',
    '''Shark, Small''',
    '''Shark, Small''',
    '''Shroom''',
    '''Skyger''',
    '''Slitherat''',
    '''Slug of P'Nahk, Giant''',
    '''Small  Medium Large''',
    '''Small  Medium Large''',
    '''Snap-Snatcher''',
    '''Sorcery Leech''',
    '''Spider, Flagstone''',
    '''Spider, Giant (1HD)''',
    '''Spider, Giant (2HD)''',
    '''Spider, Giant (4HD)''',
    '''Spider, Giant Invisible''',
    '''Spider, Giant Phase''',
    '''Spine Rat''',
    '''Spire Monkey''',
    '''Strangle Vine''',
    '''Sumatran Rat-Ghoul''',
    '''Syanngg''',
    '''Sycorex''',
    '''Tiger, Sabre-Tooth''',
    '''Titan, Cursed''',
    '''Toad, Giant Horned''',
    '''Toad, Hydra''',
    '''Toad-Men''',
    '''Triton''',
    '''Triton, Dark''',
    '''Vampire Tree''',
    '''Vapor Crane, Fledgling''',
    '''Vapor Crane, Large Adult''',
    '''Vapor Crane, Small Adult''',
    '''Were-Mist''',
    '''Wight, Sea''',
    '''Will-o'-the-Wisp''',
    '''Xole''',
    '''Yith, Hound of''',
    '''Yurmp''',
    '''Zetan''',
    '''Zombie, Brain-Eating''',

## S&W Complete
    '''Ant, Giant (Queen)''',
    '''Ant, Giant (Warrior)''',
    '''Ant, Giant (Worker)''',
    '''Badger, Giant''',
    '''Banshee''',
    '''Basilisk''',
    '''Bat, Giant''',
    '''Bat, Giant Monster''',
    '''Bat, Giant Vampire''',
    '''Bear, Black''',
    '''Beetle, Giant Fire''',
    '''Blink Dog''',
    '''Boar, Wild''',
    '''Bugbear''',
    '''Bulette''',
    '''Carrion Creeper''',
    '''Centaur''',
    '''Centipede, Giant (Greater)''',
    '''Centipede, Giant (Man-sized)''',
    '''Centipede, Giant (Small, Lethal)''',
    '''Centipede, Giant (Small, Non-lethal)''',
    '''Chimera''',
    '''Cockatrice''',
    '''Crocodile, Giant or Sea''',
    '''Crocodile, Normal''',
    '''Demon, Arauk''',
    '''Demon, Baalroch''',
    '''Demon, Dretch''',
    '''Demon, Erinyes''',
    '''Demon, Glabrezu''',
    '''Demon, Hezrou''',
    '''Demon, Khavorr''',
    '''Demon, Larvaxu''',
    '''Demon, Lemures''',
    '''Demon Lord, Isclaadra (Prince of Mists)''',
    '''Demon Lord, Kharkazax (Prince of Carrion)''',
    '''Demon Lord, Teratashia (Princess of Dimensions)''',
    '''Demon Lord, Thalasskoptis (The Sea-Demon Lord)''',
    '''Demon Lord, Yildraathu (Lord of Pestilence)''',
    '''Demon, Manes''',
    '''Demon, Marilith''',
    '''Demon, Nalfeshnee''',
    '''Demon, Quasit''',
    '''Demon, Shaavazi''',
    '''Demon, Succubus''',
    '''Demon, Vrock''',
    '''Djinni''',
    '''Doppelganger''',
    '''Dragon, Black''',
    '''Dragon, Blue''',
    '''Dragon, Gold''',
    '''Dragon, Green''',
    '''Dragon, Red''',
    '''Dragon Turtle''',
    '''Dragon, White''',
    '''Dryad''',
    '''Dwarf''',
    '''Efreeti''',
    '''Elemental, Air''',
    '''Elemental, Earth''',
    '''Elemental, Fire''',
    '''Elemental, Water''',
    '''Elf''',
    '''Fish, Giant''',
    '''Gargoyle''',
    '''Gelatinous Cube''',
    '''Ghoul''',
    '''Giant, Cloud''',
    '''Giant, Fire''',
    '''Giant, Frost''',
    '''Giant, Hill''',
    '''Giant, Stone''',
    '''Giant, Storm''',
    '''Gnoll''',
    '''Goblin''',
    '''Golem, Clay''',
    '''Golem, Flesh''',
    '''Golem, Iron''',
    '''Golem, Stone''',
    '''Gorgon''',
    '''Green Slime''',
    '''Griffon''',
    '''Harpy''',
    '''Hell Hound''',
    '''Hippogriff''',
    '''Hobgoblin''',
    '''Horse, Riding''',
    '''Horse, War''',
    '''Human, Bandit''',
    '''Human, Berserker''',
    '''Human, Normal''',
    '''Human, Sergeant-at-Arms''',
    '''Human, Soldier''',
    '''Hydra''',
    '''Invisible Stalker''',
    '''Kobold''',
    '''Leech, Giant''',
    '''Lich''',
    '''Lion''',
    '''Lizardman''',
    '''Lurker, Ceiling''',
    '''Lycanthrope, Werebear''',
    '''Lycanthrope, Wereboar''',
    '''Lycanthrope, Wererat''',
    '''Lycanthrope, Weretiger''',
    '''Lycanthrope, Werewolf''',
    '''Manticore''',
    '''Medusa''',
    '''Merman''',
    '''Minotaur''',
    '''Mummy''',
    '''Naga, Guardian''',
    '''Naga, Spirit''',
    '''Naga, Water''',
    '''Nixie''',
    '''Ochre Jelly''',
    '''Octopus, Giant''',
    '''Ogre''',
    '''Ogre Mage''',
    '''Ooze, Grey''',
    '''Orc''',
    '''Owlbear''',
    '''Pegasus''',
    '''Piercer''',
    '''Pudding, Black''',
    '''Purple Worm''',
    '''Rakshasa''',
    '''Rat, Giant''',
    '''Rat, Huge''',
    '''Roc''',
    '''Salamander''',
    '''Sea Monster''',
    '''Sea Serpent''',
    '''Shadow''',
    '''Shambling Mound''',
    '''Shrieker''',
    '''Skeleton''',
    '''Slithering Tracker''',
    '''Slug, Giant''',
    '''Spectre''',
    '''Spider, Giant (1HD)''',
    '''Spider, Giant (2HD)''',
    '''Spider, Giant (4HD)''',
    '''Spider, Giant Phase''',
    '''Squid, Giant''',
    '''Stirge''',
    '''Tick, Giant''',
    '''Titan''',
    '''Trapper Beast''',
    '''Treant''',
    '''Troll''',
    '''Unicorn''',
    '''Vampire''',
    '''Wight''',
    '''Will-o-the-Wisp''',
    '''Wolf''',
    '''Wolf, Worg''',
    '''Wraith''',
    '''Wyvern''',
    '''Yeti''',
    '''Zombie''',

## Monster Compendium
    '''Aardvark, Giant''',
    '''Aboleth''',
    '''Adult Linnorm (7HD)''',
    '''Air Gust''',
    '''Allip''',
    '''Animated Carpet''',
    '''Animated Chair''',
    '''Ankheg (3HD)''',
    '''Ankheg (4HD)''',
    '''Ankheg (5HD)''',
    '''Ankheg (6HD)''',
    '''Ape, Flying''',
    '''Ape, Gorilla''',
    '''Aqueous Orb''',
    '''Aranea''',
    '''Arcanix, Greater''',
    '''Arcanix, Major''',
    '''Arcanix, Minor''',
    '''Archer-Tree''',
    '''Artificer of Yothri''',
    '''Assassin Vine''',
    '''Athatch''',
    '''Azer''',
    '''Baboon''',
    '''Baboon (alpha male)''',
    '''Baboon, Giant''',
    '''Baboon, Giant (alpha male)''',
    '''Badger, Giant''',
    '''Bag of Teeth''',
    '''Barracuda''',
    '''Basilisk, Desert''',
    '''Bat, Giant''',
    '''Bat, Monster''',
    '''Bear, Black''',
    '''Bear, Cave/Polar''',
    '''Bear, Grizzly''',
    '''Beetle, Giant''',
    '''Beetle, Giant Arcane''',
    '''Beetle, Giant Fire''',
    '''Beetle, Giant HuHu''',
    '''Behir''',
    '''Birhaakaman''',
    '''Black Hunter''',
    '''Boar, Wild''',
    '''Bone Mound''',
    '''Borsin''',
    '''Camel''',
    '''Cat, Feral Undead''',
    '''Catoblepas''',
    '''Cave eel''',
    '''Ceiling Lurker''',
    '''Centipede Swarm''',
    '''Chaos Knight''',
    '''Clawed Fiend''',
    '''Cliessid''',
    '''Coral Clamper''',
    '''Couatl''',
    '''Cow/Ox''',
    '''Crab, Giant''',
    '''Crabmen''',
    '''Crabnipede''',
    '''Crocodile''',
    '''Crocodile, Giant''',
    '''Crumbler''',
    '''Crystal Growth''',
    '''Crystaline''',
    '''Darakel''',
    '''Darkmantle''',
    '''Deasic (Ice Creeper)''',
    '''Demon, Achaierai''',
    '''Demon, Baalroch''',
    '''Demon, Dretch''',
    '''Demon, Erinyes''',
    '''Demon, Glabrezu''',
    '''Demon, Grimlek''',
    '''Demon, Hezrou''',
    '''Demon, Lemure''',
    '''Demon, Manes''',
    '''Demon, Marilith''',
    '''Demon, Nalfeshnee''',
    '''Demon Prince, Orcus''',
    '''Demon, Vrock Demon''',
    '''Dergenue''',
    '''Dertesha''',
    '''Dhezik''',
    '''Dinosaur, Ankylosaurus''',
    '''Dinosaur, Brontosaurus''',
    '''Dinosaur, Elasmosaurus''',
    '''Dinosaur, Stegosaurus''',
    '''Dinosaur, Triceratops''',
    '''Dinosaur, Tyrannosaurus Rex''',
    '''Dog, Guard''',
    '''Dolphin''',
    '''Doppelganger''',
    '''Dragolem''',
    '''Dragonne''',
    '''Drider''',
    '''Druid (12HD)''',
    '''Druid (4HD)''',
    '''Druid (8HD)''',
    '''Dwelver''',
    '''Eagle, Giant''',
    '''Eel, Electric Giant''',
    '''Eel, Moray Giant''',
    '''Elephant''',
    '''Ethereal Shade''',
    '''Ettercap''',
    '''Ettin''',
    '''Exoskeleton, Giant Ant''',
    '''Exoskeleton, Giant Beetle''',
    '''Exoskeleton, Giant Crab''',
    '''Exploding Bones''',
    '''Eyeless Filcher''',
    '''Falshantog-yoth - The Hungering Vines''',
    '''Felikaur''',
    '''Ferec''',
    '''Fly, Carrion''',
    '''Flying Jellyfish, Giant''',
    '''Flying Squirrel, Carnivorous''',
    '''Formian, Male''',
    '''Formian, Queen''',
    '''Formian, Taskmaster''',
    '''Formian, Warrior''',
    '''Formian, Worker''',
    '''Fossil Skeleton''',
    '''Fox Monk''',
    '''Frog, Giant (1HD)''',
    '''Frog, Giant (2HD)''',
    '''Frog, Giant (3HD)''',
    '''Frog, Giant Killer''',
    '''Froglum''',
    '''Fungal Creeper''',
    '''Fungi, Violet''',
    '''Furious Fountain''',
    '''Ghast''',
    '''Ghoul, Ao-nyobo''',
    '''Giant, Cloud''',
    '''Giant, Fire''',
    '''Giant, Frost''',
    '''Giant, Hill''',
    '''Giant, Stone''',
    '''Giant, Storm''',
    '''Gibbering Mouther''',
    '''Gillmonkey''',
    '''Glass Butterfly''',
    '''Glitterskull''',
    '''Glurm (Zen frog)''',
    '''Goat, Giant''',
    '''Goblin, Belfry''',
    '''Goblin, Belfry Vampiric''',
    '''Goblin, Oni-aka''',
    '''Goblin, Oni-kage''',
    '''Goblin, Oni-yama''',
    '''Goblin, Redcap''',
    '''Golem, Clay''',
    '''Golem, Flesh''',
    '''Golem, Iron''',
    '''Golem, Stone''',
    '''Golem, Wax''',
    '''Gravebird''',
    '''Great Lantern Worm''',
    '''Grick''',
    '''Grue''',
    '''Grue, Chaos''',
    '''Gump''',
    '''Gwurrum''',
    '''Hag, Annis''',
    '''Hag, Mountain''',
    '''Hag, Night''',
    '''Hag, Sea''',
    '''Hawktoad''',
    '''Headless Hound''',
    '''Head-stealer''',
    '''Hell Hound (4HD)''',
    '''Hell Hound (5HD)''',
    '''Hell Hound (6HD)''',
    '''Hell Hound (7HD)''',
    '''Hieroglyphicroc''',
    '''Homunculus''',
    '''Hound of Yith''',
    '''Hounds of Chronos''',
    '''Human, Bandit''',
    '''Human, Berserker''',
    '''Human, Sergeant-at-Arms''',
    '''Human, Soldier''',
    '''Hydra (10 headed)''',
    '''Hydra (11 headed)''',
    '''Hydra (12 headed)''',
    '''Hydra (5 headed)''',
    '''Hydra (6 headed)''',
    '''Hydra (7 headed)''',
    '''Hydra (8 headed)''',
    '''Hydra (9 headed)''',
    '''Hyena''',
    '''Hyena, Giant''',
    '''Hypnotic Jellyfish''',
    '''Igniguana''',
    '''Imp''',
    '''Inaed''',
    '''Inner child''',
    '''IOUNifier''',
    '''Jackal''',
    '''Jackal of Darkness''',
    '''Jack-in-the-Box''',
    '''Janni''',
    '''Keeper of the Well''',
    '''Kheph, Elder''',
    '''Kheph, Mage''',
    '''Kheph, Priest''',
    '''Kheph, Warrior''',
    '''Ki-rin''',
    '''Ko'haai''',
    '''Koi Folk''',
    '''Komodo Dragon''',
    '''Komodo Dragon, Giant''',
    '''Kraken''',
    '''Kurok-Spirit''',
    '''KZADDICH''',
    '''Lamia''',
    '''Lamprey, Giant''',
    '''Lamprey, Lightning''',
    '''Leaping Maw''',
    '''Leech, Giant (1HD)''',
    '''Leech, Giant (2HD)''',
    '''Leech, Giant (3HD)''',
    '''Leech, Giant (4HD)''',
    '''Leech, Giant (5HD)''',
    '''Leech, Giant (6HD)''',
    '''Leopard''',
    '''Lephane''',
    '''Leucrota''',
    '''Lich (12HD)''',
    '''Lich (13HD)''',
    '''Lich (14HD)''',
    '''Lich (15HD)''',
    '''Lich (16HD)''',
    '''Lich (17HD)''',
    '''Lich (18HD)''',
    '''Lithonnite''',
    '''Lizard, Giant''',
    '''Lizard, Lightning''',
    '''Lizard Samurai''',
    '''Lizard Samurai Captain''',
    '''Lynx, Giant''',
    '''Macaw, Giant''',
    '''Maggog''',
    '''Malcarna''',
    '''Malformian''',
    '''Man of Bronze (captain)''',
    '''Man of Bronze (hoplite)''',
    '''Man of Bronze (lieutenant)''',
    '''Man of Bronze (sergeant)''',
    '''Manta Ray, Giant''',
    '''Marrosian Statue''',
    '''Maun-Ge''',
    '''Melgara''',
    '''Melhukiskata''',
    '''Mimic''',
    '''Mind Eater''',
    '''Mirror Fiend''',
    '''Mogura-jin''',
    '''Mold, Brown''',
    '''Mold, Yellow''',
    '''Monkey, Spire''',
    '''Monstrous Mouth''',
    '''Mothdog''',
    '''Mothmere''',
    '''Mushroom-Men''',
    '''Naga, Guardian''',
    '''Naga, Hanu (5HD)''',
    '''Naga, Hanu (6HD)''',
    '''Naga, Spirit''',
    '''Naga, Water''',
    '''Nightmare''',
    '''Nykoul''',
    '''Nymph''',
    '''Oblivion Wraith''',
    '''Octopus, Giant''',
    '''Oculaktis''',
    '''Ogre, Tusken''',
    '''Oktomon''',
    '''Old Crawler''',
    '''Omgoth''',
    '''Origami Warrior''',
    '''Ostrich, Giant''',
    '''Otyugh''',
    '''Owl, Giant''',
    '''Peryton''',
    '''Piercer (1HD)''',
    '''Piercer (2HD)''',
    '''Piercer (3HD)''',
    '''Piercer (4HD)''',
    '''Pixie''',
    '''Portal Camel''',
    '''Praying Mantis, Giant''',
    '''Pseudo-dragon''',
    '''Pudding, Black''',
    '''Quasit''',
    '''Ragged Craw''',
    '''Ranine''',
    '''Rat, Desongnol''',
    '''Rat, Giant''',
    '''Rat, Huge''',
    '''Rat, Lab''',
    '''Ratling''',
    '''Rat, Spine''',
    '''Raven, Giant''',
    '''Raven, Zombie''',
    '''Razor Wings''',
    '''Recurser''',
    '''Reef Walker''',
    '''Remorhaz (10HD)''',
    '''Remorhaz (11HD)''',
    '''Remorhaz (12HD)''',
    '''Remorhaz (13HD)''',
    '''Remorhaz (8HD)''',
    '''Remorhaz (9HD)''',
    '''Retriever''',
    '''Rhinoceros''',
    '''Rock Weasel''',
    '''Roper (10HD)''',
    '''Roper (11HD)''',
    '''Roper (12HD)''',
    '''Rot Grub''',
    '''Rothran''',
    '''Rottentail''',
    '''Rusalka''',
    '''Rust Monster''',
    '''Sahuagin''',
    '''Sand Screamer''',
    '''Satyr''',
    '''Scorpion, Giant''',
    '''Sea Cat''',
    '''Sea Horse, Giant (3HD)''',
    '''Sea Horse, Giant (4HD)''',
    '''Sea Lion''',
    '''Shadow Mastiff''',
    '''Shambling Mound (10HD)''',
    '''Shambling Mound (11HD)''',
    '''Shambling Mound (12HD)''',
    '''Shambling Mound (7HD)''',
    '''Shambling Mound (8HD)''',
    '''Shambling Mound (9HD)''',
#    '''Shark, Giant (13HD)''',
#    '''Shark, Large (7HD)''',
#    '''Shark, Large (8HD)''',
#    '''Shark, Medium (5HD)''',
#    '''Shark, Medium (6HD)''',
#    '''Shark, Small (3HD)''',
#    '''Shark, Small (4HD)''',
    '''Shocker Lizard''',
    '''Shrangaathi''',
    '''Silent Knight''',
    '''Skarusoi''',
    '''Skeletal Fury''',
    '''Skullmural''',
    '''Skunk, Giant''',
    '''Sky Worm''',
    '''Slitherats''',
    '''Sloorg''',
    '''Slug, Giant''',
    '''Snake, Cobra''',
    '''Snake, Constrictor''',
    '''Snake, Giant Amphisbaena''',
    '''Snake, Giant Constrictor''',
    '''Snake, Giant Poisonous''',
    '''Snake, Giant Spitting''',
    '''Snake, Javelin''',
    '''Snake, Viper''',
    '''Sorcerer Ox''',
    '''Sorcery Leeches''',
    '''Soulspinner''',
    '''Spectral Scavenger''',
    '''Spectre''',
    '''Spectre, Parasitic''',
    '''Sphinx, Androsphinx''',
    '''Sphinx, Criosphinx''',
    '''Sphinx, Gynosphinx''',
    '''Sphinx, Hieracosphinx''',
    '''Spider, Giant (1HD)''',
    '''Spider, Giant (2HD)''',
    '''Spider, Giant (4HD)''',
    '''Spider, Giant Invisible''',
    '''Spiderweed''',
    '''Squid, Giant''',
    '''Squid, Giant Aerial''',
    '''Stag, Giant''',
    '''Star-Mouthed Worm''',
    '''Sting Ray''',
    '''Stoneflower''',
    '''Sumatran rat-ghoul''',
    '''Sycorex''',
    '''Tangle Weed/Strangle Vine''',
    '''Tatzelworm''',
    '''Tendriculos''',
    '''Thelidu''',
    '''Thugtoad''',
    '''Thylacine''',
    '''Tick, Giant''',
    '''Tiger''',
    '''Tiger, Sabre-tooth''',
    '''Toad, Giant''',
    '''Toad, Giant Ice''',
    '''Toad, Giant Poisonous''',
    '''Todawan Master''',
    '''Torthri''',
    '''Trapper Beast (10HD)''',
    '''Trapper Beast (11HD)''',
    '''Trapper Beast (12HD)''',
    '''Treacherous Treasure''',
    '''Treant (10HD)''',
    '''Treant (11HD)''',
    '''Treant (12HD)''',
    '''Treant (7HD)''',
    '''Treant (8HD)''',
    '''Treant (9HD)''',
    '''Tree Ghost''',
    '''Triton''',
    '''Troglodyte''',
    '''Tsalakian''',
    '''Tunnel Prawn''',
    '''Turtle, Giant Sea''',
    '''Turtle, Giant Snapping (10HD)''',
    '''Turtle, Giant Snapping (8HD)''',
    '''Turtle, Giant Snapping (9HD)''',
    '''Urrslumber''',
    '''Uruak (Scrap Gnoll)''',
    '''Vampire (7HD)''',
    '''Vampire (8HD)''',
    '''Vampire (9HD)''',
    '''Vampire Tree/Jubokko''',
    '''Vapor Crane (Fledgling)''',
    '''Vapor Crane (Large Adult)''',
    '''Vapor Crane (Small Adult)''',
    '''Vargouille''',
    '''Vierd''',
    '''Walking Slime''',
    '''Wandering Hole''',
    '''Wasp, Giant''',
    '''Weasel, Giant''',
    '''Werebear''',
    '''Wereboar''',
    '''Wererat''',
    '''Weretiger''',
    '''Were-weasel''',
    '''Werewolf''',
    '''Whale, Killer''',
    '''Whale, Sperm''',
    '''Will-o-the-wisp''',
    '''Wolf, Winter''',
    '''Wolverine''',
    '''Wolverine, Giant''',
    '''Wooly Rhinoceros''',
    '''Xorn''',
    '''Yaruga''',
#    '''Ygg''',
    '''Yienhool''',
    '''Yurmp''',
    '''Yurmp, Wrestler''',
    '''Zetan (Leader)''',
    '''Zetan (Worker)''',
    '''Zombie, Brain-eating''',
    '''Zombie, Leper''',
    '''Zombie, Pyre''',

## ToH Complete
    '''Aagash "The Broken"''',
    '''Aberrant''',
    '''Abomination''',
    '''Abomination, Owlephant''',
    '''Abomination, Tigrilla''',
    '''Abyssal Harvester''',
    '''Abyssal Larva''',
    '''Adamantine Wasp Swarm''',
    '''Adherer''',
    '''Aerial Servant''',
    '''Afanc''',
    '''Ahlinni (Cackle Bird)''',
    '''Algoid''',
    '''Al-mi'raj''',
    '''Amphisbaena''',
    '''Amphisbaena Basilisk''',
    '''Anemone, Great Sea''',
    '''Angel, Chalkydri''',
    '''Angel, Empyreal''',
    '''Angel, Monadic Deva''',
    '''Angel, Movanic Deva''',
    '''Animal Lord, Cat Lord''',
    '''Animal Lord, Mouse Lord''',
    '''Ant Lion''',
    '''Apparition''',
    '''Arach''',
    '''Arcanoplasm''',
    '''Archer Bush''',
    '''Archerfish, Giant''',
    '''Asagin "The Assassin"''',
    '''Ascomoid''',
    '''Asrai''',
    '''Assassin Bug, Giant''',
    '''Astral Shark''',
    '''Atomie''',
    '''Aurumvorax (Golden Gorger)''',
    '''Axe Beak''',
    '''Babbler''',
    '''Baccae''',
    '''Banderlog''',
    '''Baobhan Sith''',
    '''Barbegazi (Ice Gnome)''',
    '''Baric''',
    '''Barracuda, Giant''',
    '''Barracuda, Medium''',
    '''Barracuda, Small''',
    '''Basidirond''',
    '''Basilisk, Crimson''',
    '''Basilisk, Greater''',
    '''Bat, Doombat''',
    '''Bat, Mobat''',
    '''Beast of Chaos''',
    '''Bedlam''',
    '''Beetle, Giant Blister''',
    '''Beetle, Giant Boring''',
    '''Beetle, Giant Death Watch''',
    '''Beetle, Giant Rhinoceros''',
    '''Beetle, Giant Saw-Toothed''',
    '''Beetle, Giant Slicer''',
    '''Beetle, Giant Water''',
    '''Beetle, Requiem''',
    '''Belabra (Tangler)''',
    '''Bhuta''',
    '''Biclops''',
    '''Bleeding Horror''',
    '''Blindheim''',
    '''Blood Bush''',
    '''Blood Hawk''',
    '''Bloodsuckle''',
    '''Bloody Bones''',
    '''Boalisk''',
    '''Bog Beast''',
    '''Bog Creeper''',
    '''Bogeyman''',
    '''Boggart''',
    '''Bog Mummy''',
    '''Bone Cobbler''',
    '''Boneneedle''',
    '''Bonesnapper''',
    '''Bonesucker''',
    '''Bookworm''',
    '''Brass Man''',
    '''Brontotherium''',
    '''Brownie''',
    '''Brume''',
    '''Brykolakas''',
    '''Buckawn''',
    '''Bumblebee, Giant Queen''',
    '''Bumblebee, Giant Worker''',
    '''Bunyip''',
    '''Burning Dervish''',
    '''Cadaver''',
    '''Cadaver Lord''',
    '''Caracal''',
    '''Carbuncle''',
    '''Caribe, Giant''',
    '''Carrion Moth''',
    '''Caryatid Column''',
    '''Caterprism''',
    '''Caterwaul''',
    '''Catfish, Giant Electric''',
    '''Cat, Golden''',
    '''Cave Cricket''',
    '''Cave Fisher''',
    '''Cave Moray''',
    '''Cerberus''',
    '''Cerebral Stalker''',
    '''Chaadon "The Slayer"''',
    '''Chaas "The Flayed"''',
    '''Chain Worm''',
    '''Chameleon, Giant''',
    '''Chameleon, Giant Horned''',
    '''Chameleon, Rock''',
    '''Cherum''',
    '''Chrystone''',
    '''Chupacabra''',
    '''Church Grim''',
    '''Churr''',
    '''Clam, Giant''',
    '''Clamor''',
    '''Clockwork Brain Gear''',
    '''Clockwork Bronze Giant''',
    '''Clockwork Drone''',
    '''Clockwork Overseer''',
    '''Clockwork Parasite''',
    '''Clockwork Scout''',
    '''Clockwork Swarm''',
    '''Clockwork Titan''',
    '''Clockwork Warrior''',
    '''Clubnek''',
    '''Cobra Flower''',
    '''Coffer Corpse''',
    '''Common Mite''',
    '''Common Time Elemental''',
    '''Common Tsathar''',
    '''Cooshee''',
    '''Corpse Candle''',
    '''Corpse Orgy''',
    '''Corpse Rook''',
    '''Corpsespinner''',
    '''Crab, Fire (1HD)''',
    '''Crab, Fire (3HD)''',
    '''Crabman''',
    '''Crab, Monstrous''',
    '''Crag Man''',
    '''Crayfish, Monstrous''',
    '''Crucifixion Spirit''',
    '''Crypt Thing''',
    '''Crystalline Horror''',
    '''Crystallis''',
    '''Daemon, Cacodaemon''',
    '''Daemon, Charon''',
    '''Daemon, Charonadaemon''',
    '''Daemon, Derghodaemon''',
    '''Daemon, Guardian''',
    '''Daemon, Hydrodaemon''',
    '''Daemon, Piscodaemon''',
    '''Daemon, The Oinodaemon''',
    '''Dakon''',
    '''Dark Creeper''',
    '''Dark Stalker''',
    '''Darnoc''',
    '''Death Dog''',
    '''Death Worm''',
    '''Decapus''',
    '''Deer''',
    '''Deer, Onyx''',
    '''Demi-Lich''',
    '''Demiurge''',
    '''Demodand, Shaggy''',
    '''Demodand, Slime''',
    '''Demodand, Tarry''',
    '''Demon, Aeshma (Rage Demon)''',
    '''Demon, Alu-Demon''',
    '''Demon, Balban (Brute Demon)''',
    '''Demon, Cambion''',
    '''Demon, Chaaor (Beast Demon)''',
    '''Demon, Choronzon (Chaos Demon)''',
    '''Demon, Corruptor Azizou (Pain Demon)''',
    '''Demon, Corruptor Barizou (Assassin Demon)''',
    '''Demon, Corruptor Geruzou (Slime Demon)''',
    '''Demon, Daraka (Swarm Demon)''',
    '''Demon, Demonling Nabasu''',
    '''Demon, Gallu-Demon (Faceless Demon)''',
    '''Demon, Gharros (Scorpion Demon)''',
    '''Demon, Greruor (Frog Demon)''',
    '''Demonic Knight''',
    '''Demon Lord, Baphomet (Lord of Beasts)''',
    '''Demon Lord, Beluiri (The Temptress)''',
    '''Demon Lord, Caizel (Deposed Queen of Succubi)''',
    '''Demon Lord, Dagon (Prince of the Sea)''',
    '''Demon Lord, Fraz-Urb'luu (Prince of Deception)''',
    '''Demon Lord, Jubilex (The Faceless Lord)''',
    '''Demon Lord, Kostchtchie (Prince of Wrath)''',
    '''Demon Lord, Maphistal (Second of Orcus)''',
    '''Demon Lord, Orcus (Prince of the Undead)''',
    '''Demon Lord, Pazuzu (Prince of Air)''',
    '''Demon Lord, Sonechard (General of Orcus)''',
    '''Demon Lord, Tsathogga (The Frog God)''',
    '''Demon Lord, Vepar (Duke of Dagon)''',
    '''Demon, Mallor (Serpent Demon)''',
    '''Demon, Mature Nabasu''',
    '''Demon, Mehrim (Goat Demon)''',
    '''Demon, Mezzalorn (Wasp Demon)''',
    '''Demon, Nerizo (Hound Demon)''',
    '''Demon, Nysrock (Cobra Demon)''',
    '''Demon, Ooze (Greater)''',
    '''Demon, Ooze (Lesser)''',
    '''Demon, Shadow''',
    '''Demon, Shrroth (Squid Demon)''',
    '''Demon, Skitterdark''',
    '''Demon, Stirge''',
    '''Devil, Alastor (Executioner of Hell)''',
    '''Devil, Amaimon''',
    '''Devil, Amon (Duke of Hell)''',
    '''Devil, Baal (Duke of Hell)''',
    '''Devil, Baaphel (Duke of Hell)''',
    '''Devil, Blood Reaver (Garugin)''',
    '''Devil, Caasimolar (Former President of Hell)''',
    '''Devil, Demoriel (Twice-Exiled Seductress)''',
    '''Devil Dog''',
    '''Devil, Flayer (Marzach)''',
    '''Devil, Geryon (Arch-Devil)''',
    '''Devil, Ghaddar''',
    '''Devil, Gorson (The Blood Duke)''',
    '''Devil, Hellstoker (Marnasoth)''',
    '''Devil, Hutijin (Duke of Hell)''',
    '''Devil, Lilin''',
    '''Devil, Lilith (Former Queen of Hell)''',
    '''Devil, Lucifer (Prince of Darkness)''',
    '''Devil, Moloch (Arch-Devil)''',
    '''Devil, Nupperibo''',
    '''Devil, Titivilus (Duke of Hell)''',
    '''Devil, Tormentor of Souls''',
    '''Devil, Xaphan (Duke of Infernus)''',
    '''Diger''',
    '''Dire Bison''',
    '''Dire Corby''',
    '''Dire Deer''',
    '''Dire Dog''',
    '''Dire Elephant''',
    '''Dire Ghoul Wolf''',
    '''Dire Goat''',
    '''Dire Hippopotamus (Behemoth)''',
    '''Dire Moose''',
    '''Dire Porcupine''',
    '''Dire Ram''',
    '''Dire Skunk''',
    '''Dire Sloth''',
    '''Disenchanter''',
    '''Dracolisk''',
    '''Draconid''',
    '''Dragon, Cloud''',
    '''Dragon, Dungeon''',
    '''Dragon, Faerie''',
    '''Dragonfish''',
    '''Dragonfly, Giant''',
    '''Dragon Horse''',
    '''Dragon, Mist''',
    '''Dragonnel''',
    '''Dragonship''',
    '''Dragon, Smoke''',
    '''Dragon, Wrath''',
    '''Drake, Fire''',
    '''Drake, Ice''',
    '''Drake, Salt''',
    '''Drake, Splinter''',
    '''Draug''',
    '''Dream Spectre''',
    '''Drelb''',
    '''Dust Digger''',
    '''Ear Seeker''',
    '''Eblis''',
    '''Ectoplasm''',
    '''Eel, Electric''',
    '''Eel, Giant Moray''',
    '''Eel, Gulper''',
    '''Elemental Construct, Air''',
    '''Elemental Construct, Earth''',
    '''Elemental Construct, Fire''',
    '''Elemental Construct, Water''',
    '''Elemental Dragon, Air''',
    '''Elemental Dragon, Earth''',
    '''Elemental Dragon, Fire''',
    '''Elemental Dragon, Water''',
    '''Elemental, Gravity''',
    '''Elemental, Negative Energy''',
    '''Elemental, Positive Energy''',
    '''Elemental, Psionic''',
    '''Elusa Hound''',
    '''Encephalon Gorger''',
    '''Executioner's Hood''',
    '''Eye Killer''',
    '''Eye of the Deep''',
    '''Falcon, Giant''',
    '''Fear Guard''',
    '''Fen Witch''',
    '''Fetch''',
    '''Firefiend''',
    '''Fire Phantom''',
    '''Flea, Giant''',
    '''Flea, Giant Phase''',
    '''Floating Eye''',
    '''Flumph''',
    '''Fly, Giant''',
    '''Fogwarden''',
    '''Foo Dog''',
    '''Forester's Bane''',
    '''Forgotten One''',
    '''Forlarren''',
    '''Fox''',
    '''Frog, Giant''',
    '''Frog, Giant Abyssal Dire''',
    '''Frog, Giant Dire''',
    '''Froghemoth''',
    '''Frog, Killer''',
    '''Frog, Poisonous''',
    '''Frost Man''',
    '''Fulgurate Mushrooms''',
    '''Fungi, Sheet''',
    '''Fungoid''',
    '''Fye''',
    '''Fyr''',
    '''Gallows Tree''',
    '''Gallows Tree Zombie''',
    '''Gambado''',
    '''Gargoyle, Four-Armed''',
    '''Gargoyle, Fungus''',
    '''Gargoyle, Green Guardian''',
    '''Gargoyle, Margoyle''',
    '''Gas Spore''',
    '''Gelid Beetle (Greater)''',
    '''Gelid Beetle (Lesser)''',
    '''Genie, Abasheen''',
    '''Genie, Hawanar''',
    '''Genie, Marid''',
    '''Geon''',
    '''Ghehzi "The Mutilator"''',
    '''Ghoul, Cinder''',
    '''Ghoul, Dust''',
    '''Ghoul-Stirge''',
    '''Giant, Bronze''',
    '''Giant, Cave''',
    '''Giant, Ferrous''',
    '''Giant, Jack-In-Irons''',
    '''Giant, Sand''',
    '''Giant, Sea''',
    '''Giant, Smoke''',
    '''Giant, Volcano''',
    '''Giant, Wood''',
    '''Glass Wyrm''',
    '''Gloom Crawler''',
    '''Gloomwing''',
    '''Gnarlwood''',
    '''Gnoll, Flind''',
    '''Gohl (Hydra Cloud)''',
    '''Golem, Blood''',
    '''Golem, Flagstone''',
    '''Golem, Furnace''',
    '''Golem, Gelatinous''',
    '''Golem, Ice''',
    '''Golem, Iron Maiden''',
    '''Golem, Magnesium''',
    '''Golem, Mummy''',
    '''Golem, Ooze''',
    '''Golem, Rope''',
    '''Golem, Stone Guardian''',
    '''Golem, Tallow''',
    '''Golem, Witch-Doll''',
    '''Golem, Wood''',
    '''Gorbel''',
    '''Gorgimera''',
    '''Gorilla Bear''',
    '''Grave Risen''',
    '''Graymalkin, Common''',
    '''Graymalkin, Slinker''',
    '''Graymalkin, Tether''',
    '''Gray Nisp''',
    '''Greixas "The Destroyer"''',
    '''Gremlin''',
    '''Grig Swarm''',
    '''Grimm''',
    '''Grimstalker (Banaan)''',
    '''Grippli''',
    '''Groaning Spirit''',
    '''Gronk''',
    '''Gryph''',
    '''Gutslug''',
    '''Half-Ogre''',
    '''Hamster, Giant''',
    '''Hanged Man''',
    '''Hangman Tree''',
    '''Haunt''',
    '''Heat Swarm''',
    '''Helix Moth, Larva''',
    '''Helix Moth, Mature''',
    '''Hell Moth''',
    '''Herald of Tsathogga''',
    '''Hippocampus''',
    '''Hippopotamus''',
    '''Hoar Fox''',
    '''Hoar Spirit''',
    '''Hornet, Giant''',
    '''Horsefly, Giant''',
    '''Hound of Ill Omen''',
    '''Huecuva''',
    '''Huggermugger''',
    '''Hyaenodon''',
    '''Inphidian, Cobra-Back''',
    '''Inphidian, Common''',
    '''Inphidian, Dancer''',
    '''Inphidian, Night Adder''',
    '''Inphidian, Rattler''',
    '''Iron Cobra''',
    '''Jack-O-Lantern''',
    '''Jaculi''',
    '''Jade Colossus''',
    '''Jaguar''',
    '''Jellyfish, Monstrous''',
    '''Jelly, Mustard''',
    '''Jelly, Stun''',
    '''Jelly, Whip''',
    '''Jupiter Bloodsucker (Vampire Plant)''',
    '''Kamadan''',
    '''Kampfult (Sinewy Mugger)''',
    '''Kathlin''',
    '''Kech''',
    '''Kelp Devil''',
    '''Kelpie''',
    '''Khargra''',
    '''Killmoulis''',
    '''Korred''',
    '''Kuah-Lij''',
    '''Land Lamprey''',
    '''Landwalker Piranha Swarm''',
    '''Lantern Goat''',
    '''Lava Child''',
    '''Leech, Cave''',
    '''Leech, Giant''',
    '''Leech, Spinal''',
    '''Leech, Throat''',
    '''Leopard, Snow''',
    '''Leprechaun''',
    '''Lich Shade''',
    '''Lion, Cave''',
    '''Lion, Mountain''',
    '''Livestone''',
    '''Living Lake (Agrath-Ogh)''',
    '''Lizard, Cavern''',
    '''Lizard, Fire''',
    '''Lizard, Giant Rock-Horned''',
    '''Lizard, Gnasher''',
    '''Lurker Above''',
    '''Lynx''',
    '''Lythic''',
    '''Magmoid''',
    '''Magnesium Spirit''',
    '''Mammoth''',
    '''Mandragora''',
    '''Mandrill''',
    '''Mantari''',
    '''Mantidrake''',
    '''Margay''',
    '''Marmoset, Giant''',
    '''Marsh Jelly''',
    '''Marsh Jelly, Demonic (Progeny of Jubilex)''',
    '''Mastodon''',
    '''Mawler''',
#    '''Medusa, Greater''',
    '''Memory Child''',
    '''Memory Moss''',
    '''Mephit, Lightning''',
    '''Mephit, Smoke''',
    '''Midnight Peddler''',
    '''Mihstu''',
    '''Mimi''',
    '''Mire Brute''',
    '''Modar "The Avenger"''',
    '''Mongrelman''',
    '''Moon Dog''',
    '''Moose''',
    '''Mortuary Cyclone''',
    '''Mosquito, Giant''',
    '''Muckdweller''',
    '''Mudbog''',
    '''Mudman''',
    '''Mummy of the Deep''',
    '''Murder-Born''',
    '''Murder Crow''',
    '''Nazalor''',
    '''Necrophidius''',
    '''Nereid''',
    '''Netherspark''',
    '''N'hror "The Eater"''',
    '''Nilbog''',
    '''Niln (Vapor Horror)''',
    '''Noble Time Elemental''',
    '''Nuckalavee''',
    '''Nymph, Fire''',
    '''Oakman''',
    '''Obsidian Minotaur''',
    '''Ogren''',
    '''Ogrillon''',
    '''Oil Shark''',
    '''Oliphant''',
    '''Olive Slime''',
    '''Olive Slime Zombie''',
    '''Ooze, Amber''',
    '''Ooze, Crystal''',
    '''Ooze, Entropic''',
    '''Ooze, Entropic-Dark Matter''',
    '''Ooze, Glacial''',
    '''Ooze, Magma''',
    '''Ooze, Mercury''',
    '''Ooze, Metallic''',
    '''Ooze, Undead''',
    '''Ooze, Vampiric''',
    '''Orc, Black''',
    '''Orc, Black-High Priest of Orcus''',
    '''Orc, Blood''',
    '''Orc, Ghost-Faced''',
    '''Orc, Greenskin''',
    '''Orog''',
    '''Paleoskeleton, Triceratops''',
    '''Pech''',
    '''Pedipalp Giant False Spider''',
    '''Pestie Mite''',
    '''Phantasm''',
    '''Phantom''',
    '''Phantom Stalker''',
    '''Phasma''',
    '''Phlogiston''',
    '''Phooka''',
    '''Phycomid''',
    '''Piercer''',
    '''Pike, Giant''',
    '''Pit Hag''',
    '''Plant-Imbued Ape''',
    '''Poisonous Frog Swarm''',
    '''Poltergeist''',
    '''Proscriber''',
    '''Protector''',
    '''Psiwyrm''',
    '''Pudding, Blood''',
    '''Pudding, Brown''',
    '''Pudding, Dun''',
    '''Pudding, Stone''',
    '''Pudding, White''',
    '''Purple Moss''',
    '''Pyrolisk''',
    '''Quantum''',
    '''Quasi-Elemental, Acid (10HD)''',
    '''Quasi-Elemental, Acid (12HD)''',
    '''Quasi-Elemental, Acid (2HD)''',
    '''Quasi-Elemental, Acid (4HD)''',
    '''Quasi-Elemental, Acid (6HD)''',
    '''Quasi-Elemental, Acid (8HD)''',
    '''Quasi-Elemental, Lightning (12HD)''',
    '''Quasi-Elemental, Lightning (6HD)''',
    '''Quasi-Elemental, Lightning (9HD)''',
    '''Quasi-Elemental, Obsidian (10HD)''',
    '''Quasi-Elemental, Obsidian (12HD)''',
    '''Quasi-Elemental, Obsidian (2HD)''',
    '''Quasi-Elemental, Obsidian (4HD)''',
    '''Quasi-Elemental, Obsidian (6HD)''',
    '''Quasi-Elemental, Obsidian (8HD)''',
    '''Quickling''',
    '''Quickwood''',
    '''Quipper''',
    '''Raauka "The Ravager"''',
    '''Racoon''',
    '''Racoon, Dire''',
    '''Raggoth''',
    '''Rakklethorn Toad''',
    '''Rat, Barrow''',
    '''Rat, Brain''',
    '''Rat, Ethereal''',
    '''Rat, Shadow''',
    '''Rat, Spore''',
    '''Rat, Vapor''',
    '''Raven Swarm''',
    '''Rawbones''',
    '''Redcap''',
    '''Red Jester''',
    '''Reigon''',
    '''Reliquary Guardian''',
    '''Renzer (Devilfin)''',
    '''Retch Hound''',
    '''Rhinoceros, Woolly''',
    '''Rhinoceros, Woolly-Elasmotherium''',
    '''Riptide Horror''',
    '''Rock Reptile''',
    '''Ronus''',
    '''Roper, Stone''',
    '''Royal Time Elemental''',
    '''Ryven''',
    '''Sabrewing''',
    '''Sample N'gathau, Donlaan''',
    '''Sand Kraken''',
    '''Sandling''',
    '''Sandman''',
    '''Sand Stalker''',
    '''Scarecrow''',
    '''Scarlet Spider Swarm''',
    '''Scimitar Horn''',
    '''Screaming Devilkin''',
    '''Screaming Skull''',
    '''Scylla''',
    '''Scythe Horn''',
    '''Scythe Tree''',
    '''Seahorse, Giant''',
    '''Sea Serpent, Brine''',
    '''Sea Serpent, Deep Hunter''',
    '''Sea Serpent, Fanged''',
    '''Sea Serpent, Gilded''',
    '''Sea Serpent, Shipbreaker''',
    '''Sea Serpent, Spitting''',
    '''Sea Wasp, Monstrous''',
    '''Sepulchral Guardian''',
    '''Shadow, Lesser''',
    '''Shadow Rat Swarm''',
    '''Shark, Giant Landwalker''',
    '''Shedu (Common)''',
    '''Shedu (Greater)''',
    '''Sheep''',
    '''Sheep, Ram''',
    '''Silid''',
    '''Skeleton, Black''',
    '''Skeleton, Lead''',
    '''Skeleton Warrior''',
    '''Skin Stitcher''',
    '''Skulk''',
    '''Skulleton''',
    '''Skunk''',
    '''Slaad Lord of Entropy''',
    '''Slaad Lord of the Insane''',
    '''Slag Worm''',
    '''Slaughterford''',
    '''Sleeping Willow''',
    '''Slime Crawler''',
    '''Slime Mold''',
    '''Slithering Tracker''',
    '''Slorath''',
    '''Slug, Giant''',
    '''Slug, Giant Sea''',
    '''Smilodon, Giant''',
    '''Smilodon, Homotherium''',
    '''Smilodon (Saber-Toothed Cat)''',
    '''Snail, Flail''',
    '''Snake, Fire''',
    '''Snake, Marble''',
    '''Snake, Sepia''',
    '''Snake, Sloth Viper''',
    '''Solifugid Giant False Spider''',
    '''Soul Eater''',
    '''Soul Nibbler''',
    '''Soul Reaper''',
    '''Spectral Troll''',
    '''Spider Collective''',
    '''Spider, Sea''',
    '''Spider, Sea Pelagos''',
    '''Spider, Skull''',
    '''Spider, Wolf''',
    '''Spriggan''',
    '''Sprite''',
    '''Squealer''',
    '''Stegocentipede''',
    '''Stench Kow''',
    '''Stingray, Large''',
    '''Stingray, Medium''',
    '''Stingray, Small''',
    '''Stone Maiden''',
    '''Stormwarden''',
    '''Strangle Weed''',
    '''Stroke Lad''',
    '''Stygian Leviathan''',
    '''Stymphalian Bird''',
    '''Sudoth''',
    '''Symbiotic Jelly''',
    '''Tabaxi''',
    '''Taer''',
    '''Tangtal (Dupli-Cat)''',
    '''Tazelwurm''',
    '''Temporal Crawler''',
    '''Tendrul''',
    '''Tenebrous Worm''',
    '''Tentacled Horror''',
    '''Tentamort''',
    '''The Quorum''',
    '''Therianthrope, Asswere''',
    '''Therianthrope, Dire Wolfwere''',
    '''Therianthrope, Foxwere''',
    '''Therianthrope, Jackalwere''',
    '''Therianthrope, Lionwere''',
    '''Therianthrope, Mulewere''',
    '''Therianthrope, Owlwere''',
    '''Therianthrope, Wolfwere''',
    '''Thermite, Queen''',
    '''Thermite, Soldier''',
    '''Thermite, Worker''',
    '''Thessalgorgon''',
    '''Thessalhydra''',
    '''Thessalisk''',
    '''Thorny''',
    '''Thorny Tyrannosaurus''',
    '''Thunder Beast''',
    '''Thundershrike''',
    '''Tick, Giant''',
    '''Tiger Barb, Giant''',
    '''Time Flayer''',
    '''Tombstone Fairy''',
    '''Transposer''',
    '''Trapper''',
    '''Treant, Lightning''',
    '''Tri-Flower Frond''',
    '''Troblin''',
    '''Troll, Cave''',
    '''Troll, Flame-Spawned''',
    '''Troll, Ice''',
    '''Troll, Rock''',
    '''Troll, Swamp''',
    '''Troll, Two-Headed''',
    '''True Gorgon, Medusa''',
    '''True Gorgon, Euryale''',
    '''True Gorgon, Sthenno''',
    '''Tsathar Scourge''',
    '''T'shann''',
    '''Tuatara, Giant''',
    '''Tumblespark''',
    '''Tunnel Worm''',
    '''Turtle, Giant Bog''',
    '''Turtle, Giant Snapping''',
    '''Turtle-Shark''',
    '''Turtle-Shark, Stygian''',
    '''Twilight Mushrooms''',
    '''Ubue''',
    '''Ulaska't "The Twisted"''',
    '''Undead Raven Swarm''',
    '''Vampire Rose''',
    '''Veenes "The Blademistress"''',
    '''Vegepygmy''',
    '''Velvet Ant Swarm''',
    '''Veruard "The Razor and the Creator"''',
    '''Vilstrak''',
    '''Volt''',
    '''Vorin''',
    '''Vulchling''',
    '''Wang Liang''',
    '''Warden Jack Swarm''',
    '''Wasp, Vapor''',
    '''Weird, Blood''',
    '''Weird, Fungus''',
    '''Weird, Lava''',
    '''Weird, Lightning''',
    '''Well Lurker''',
    '''Whale, Fire''',
    '''Widow Creeper''',
    '''Wight, Barrow''',
    '''Wight, Blood''',
    '''Willow Dusk''',
    '''Wind Walker''',
    '''Winter Bloom''',
    '''Witch Grass''',
    '''Witch Tree''',
    '''Witherstench''',
    '''Witherweed''',
    '''Wizard's Shackle''',
    '''Wolf, Abyssal''',
    '''Wolf, Ghoul''',
    '''Wolf-in-Sheep's-Clothing''',
    '''Wolf, Shadow''',
    '''Woodwose''',
    '''Yellowjacket, Giant''',
    '''Yellow Musk Creeper''',
    '''Yeti''',
    '''Zombie, Brine''',
    '''Zombie, Corpsespun''',
    '''Zombie, Juju''',
    '''Zombie, Spellgorged''',
    '''Zombie, Yellow Musk''',

## Varlets and Vermin
    '''Amphibious Jumping Tiger Shark''',
    '''Barrel Beast''',
    '''Botflies, Giant''',
    '''Cerement''',
    '''Degenerates''',
    '''Elemental Nuisance: Air''',
    '''Elemental Nuisance: Earth''',
    '''Elemental Nuisance: Fire''',
    '''Elemental Nuisance: Water''',
    '''Eye Droppers''',
    '''Fardarrig''',
    '''Fungi, Saucer''',
    '''Ghost Face''',
    '''Golem, Scrap''',
    '''Greenhair''',
    '''Hoard Serpent''',
    '''Ice Nixie''',
    '''Man of Wounds''',
    '''Meat Slugs''',
    '''Mithridatium Bush''',
    '''Moth, Fire''',
    '''Pemblings''',
    '''Pillbugs, Giant''',
    '''Rat, Miner''',
    '''Rat, Panzer''',
    '''Rat, Scaler''',
    '''Rat Swarm''',
    '''Rat, Zombie''',
    '''Razor Thorns''',
    '''Skull Creeper''',
    '''Spitting Striders''',
    '''Strangle Vines''',
    '''Torpor Remora''',
    '''Translucent Worms''',
    '''Trickster Beast''',
    '''Vulture, Doom''',

## 51 from Barrowmaze I,II
    '''Human, Tomb-Robbers''',
    '''Human, Necromancer of Set''',
    '''Human, Acolyte of Orcus''',
    '''Amber Jelly''',
    '''Ant, Giant''',
    '''Barrow Guardian''',
    '''Barrow Guardian, Greater''',
#    '''Black Tentacles''',
    '''Brass Jackal''',
    '''Clockwork, Cobra''',
    '''Crab, Fire''',
    '''Crypt Knight''',
    '''Crypt Shade''',
    '''Crypt Shade, Greater''',
    '''Daughter of Gaxx''',
    '''Death Knight''',
    '''Elemental, Fountain''',
#    '''Exoskeleton''',
    '''Funeral Pyre''',
    '''Fungi, Icterine''',
    '''Gargoyle, Four-Armed''',
    '''Gargoyle, Maggog''',
    '''Gargoyle, Margoyle''',
    '''Gehennian Goat''',
    '''Ghast, Barrow''',
    '''Golem, Gemstone''',
    '''Golem, Runic''',
    '''Harpy, Barrow''',
    '''Lava Weird''',
#    '''Lich-Dragon''',
#    '''Medusa, Greater''',
    '''Mold, Amber''',
    '''Mummy, Barrow''',
    '''Mummy Lord''',
    '''Mummy of Zuul''',
    '''Neb'Enakhet''',
    '''Necrolyte of Nurgal''',
    '''Pudding, Brown''',
    '''Pudding, Rot''',
    '''Ravenous Dead''',
    '''Scorpion, Clockwork''',
    '''Scorpion, Huge''',
    '''Skeleton, Exploding Bone''',
    '''Skeleton, Fossil''',
    '''Skeleton, Sapphire''',
    '''Skeleton, Steel''',
    '''Son of Gaxx''',
    '''Spectral Dead''',
    '''Spider, Blood-Thirsty''',
    '''Vulture, Giant''',
    '''Water Fountain''',
    '''Wight, Barrow''',
    '''Zombie, Funeral Pyre''',
    '''Zombie, JuJu''',

## 75 Dwimmermount
    '''Astral Reaver''',
    '''Demon, Balor''',
    '''Demon, Glabrezu''',
    '''Jubilex (Demon Lord)''',
    '''Marilith (Demon of the Fifth Circle)''',
    '''Nalfeshnee (Demon of the Fourth Circle)''',
    '''Succubus''',
    '''Manes''',
    '''Vrock (Demon of the First Circle)''',
    '''Beetle, Boring''',
    '''Cave Kraken''',
    '''Golem, Clay''',
    '''Derrim''',
    '''Dretch''',
    '''Dwimmerdragon''',
    '''Dworg''',
    '''Eld''',
    '''Eldritch Bones''',
    '''Empyreal''',
    '''Green Guardian''',
    '''Guardian Plasm''',
    '''Intellect Devourer''',
    '''Morzaadian''',
    '''Golem, Iron Maiden''',
    '''Jellyfish Plant''',
    '''Thoonarn''',
    '''Ooze, Mercury''',
    '''Muculent Worm''',
    '''Froglock''',
    '''Roper''',
    '''Zombie, Slime''',
    '''Spawn of Arach-Nacha''',
#    '''Spider, Phase''',
    '''Golem, Stone''',
    '''Termaxian Husk''',
    '''Termaxian Mummy''',
    '''Termaxian Necrolyte''',
    '''Terrim''',
    '''Komodo Dragonmen, Two-Headed''',
    '''Golem, Turnkey''',
    '''Ooze, Undead''',
    '''Zombie, Brute''',
    ]
