colleges = {
        'M': 'Hermeticist',
        'I': 'Illusionist',
        'E': 'Elementalist',
        'N': 'Necromancer',
        'V': 'Vivimancer',
#        'W': 'Wizardry',
        'T': 'Arcane Tomes',
        'R': 'Arcane Rituals',
        'D': 'Divine',
        }
college_lookup = dict((v, k) for k, v in colleges.items())

spell_index = [
    'Hyper Healing (V)             20',
    'Hyper Immune System (V)       20',
    'Hyper Metabolism (V)          20',
    'Aerial Servant (D)                  AEC 40',
    'Allure (M)                          AEC 55',
    'Alter Reality (I)                   33',
    'Amalgam of Earth and Air (E)        4',
    'Amalgam of Fire and Water (E)       4',
    'Amnesia (M)                         AEC 55',
    'Animal Companion (V)                AEC 41',
    'Animal Growth (V)                   AEC 41',
    'Animal Growth (M)                   AEC 55',
    'Animate Dead (M)                    AEC 55',
    'Animate Dead (D)                    AEC 30',
    'Animate Mineral (M)                 AEC 41',
    'Animate Objects (D)                 AEC 31',
    'Animate Puppet, Mass (T)            39',
    'Animate Puppet (T)                  39',
    'Animate Statue (T)                  39',
    'Anti-Animal Ward (V)                AEC 41',
    'Anti-Magic Ward (M)                AEC 55',
    'Antipathy/Sympathy (M)              AEC 55',
    'Anti-Plant Ward (V)                 AEC 41',
    'Arcane Mark (T)                     40',
    'Arcane Window (T)                   AEC 56',
    'Artificial Intelligence (V)         20',
    'Ascend (T)                          46',
    'Astral Projection (R)               AEC 56',
    'Astral Projection (D)               AEC 31',
    'Atmosphere Bubble (M)               AEC 56',
    'Atonement (D)                       AEC 31',
    'Attach Rope (T)                     46',
    'Auditory Illusion (I)               AEC 49',
    'Auditory Illusion (M)               AEC 56',
    'Augury (D)                          AEC 31',
    'Banish Elemental (E)                4',
    'Banish Elementine (E)               4',
    'Barkskin (V)                        AEC 41',
    'Bind Spirit (N)                     10',
    'Blade Barrier (D)                   AEC 32',
    'Bless (D)                           AEC 32',
    'Blindness / Deafness (I)            AEC 49',
    'Blink (M)                           AEC 56',
    'Blur (I)                            AEC 50',
    'Bond Bane (T)                       46',
    'Brimstone Monolith (E)              5',
    'Burning Hands (M)                   AEC 57',
    'Call Lightning (D)                  AEC 41',
    'Cannibalize (V)                     21',
    'Cause Critical Wounds (D)           AEC 33',
    'Cause Disease (D)                   AEC 33',
    'Cause Light Wounds (D)              AEC 33',
    'Cause Serious Wounds (D)            AEC 33',
    'Channel (T)                         43',
    'Chant (D)                           AEC 36',
    'Charm Monster (M)                   AEC 57',
    'Charm Person (M)                    AEC 57',
    'Charm Animal (V)                    AEC 41',
    'Charm Plants (M)                    AEC 57',
    'Charm Spell (T)                     40',
    'Charm Undead (N)                    10',
    'Chimera III (V)                     22',
    'Chimera II (V)                      21',
    'Chimera I (V)                       21',
    'Choke (N)                           10',
    'Clairaudience (M)                   AEC 57',
    'Clairvoyance (M)                    AEC 57',
    'Hand, Clenched (T)                   AEC 57',
    'Hand, Annoying (T)                   GG',
    'Clone (M)                           AEC 58',
    'Cloudkill (M)                       AEC 58',
    'Color Spray (I)                     AEC 50',
    'Command Construct (T)               39',
    'Command Dead (N)                    11',
    'Command Elemental I (E)             5',
    'Command Elemental II (E)            5',
    'Command Elemental III (E)           6',
    'Command Rope (T)                    46',
    'Command Spell (T)                   40',
    'Command Undead (N)                  11',
    'Command (D)                         AEC 32',
    'Commune with Nature (V)             AEC 41',
    'Commune (D)                         AEC 32',
    'Read Languages (M)            AEC 58',
    'Conducting Skein (T)                46',
    'Conducting Web (T)                  46',
    'Cone of Cold (M)                    AEC 58',
    'Cone of Heat (M)                    AEC 58',
    'Conflagration (M)                   AEC 44',
    'Confusion, Greater (I)              AEC 50',
    'Confusion (I)                       AEC 50',
    'Confusion (M)                       AEC 58',
    'Conjure Animals (D)                 AEC 32',
    'Conjure Earth Elemental (V)         AEC 42',
    'Summon Elemental (R)               AEC 58',
    'Conjure Fire Elemental (V)          AEC 42',
    'Conjure Rope (T)                    46',
    'Contact Elemental Spirit (E)        6',
    'Contact Other Plane (E)             6',
    'Contact Other Plane (R)             AEC 58',
    'Contact Spirit (N)                  11',
    'Continual Darkness (M)              AEC 32',
    'Continual Darkness (D)              AEC 32',
    'Continual Light (M)                 AEC 59',
    'Continual Light (D)                 AEC 32',
    'Control Ooze (T)                    45',
    'Control Temperature (D)             AEC 48',
    'Control Weather (D)                 AEC 42',
    'Control Weather, Greater (D)        AEC 42',
    'Control Weather (M)                 AEC 59',
    'Control Weather (D)                 AEC 32',
    'Control Winds (D)                   AEC 42',
    'Corpse Visage (N)                   11',
    'Create Food and Water (D)           AEC 33',
    'Create Water (V)                    AEC 42',
    'Create Water (D)                    AEC 33',
    'Creeping Doom (V)                   AEC 42',
    'Hand, Crushing (T)                   AEC 59',
    'Cure Blindness (D)                  AEC 33',
    'Cure Critical Wounds (D)            AEC 33',
    'Cure Disease (D)                    AEC 33',
    'Cure Light Wounds (D)               AEC 33',
    'Cure Serious Wounds (D)             AEC 33',
    'Curse of Undeath (N)                11',
    'Curse (D)                    AEC 38',
    'Dancing Lights (I)                  AEC 50',
    'Dancing Lights (M)                  AEC 59',
    'Darkness (D)                        AEC 50',
    'Darkness (M)                        AEC 60',
    'Deafness (I)                        AEC 50',
    'Death Geas (N)                      11',
    'Death (M)                           AEC 60',
    'Death Recall (N)                    11',
    'Fireball, Greater (M)          AEC 60',
    'Delay Poison (D)                    AEC 33',
    'Demand (E)                          6',
    'Destruction (N)                     AEC 38',
    'Detach (N)                          11',
    'Detect Disease (N)                  12',
    'Detect Evil (M)                     AEC 60',
    'Detect Evil (D)                     AEC 33',
    'Detect Illusion (I)                 AEC 50',
    'Detect Invisible (I)                AEC 50',
    'Detect Invisible (M)                AEC 60',
    'Detect Lie (D)                      AEC 34',
    'Detect Magic (V)                    AEC 43',
    'Detect Magic (I)                    AEC 51',
    'Detect Magic (M)                    AEC 60',
    'Detect Magic (D)                    AEC 34',
    'Detect Poison (V)                   22',
    'Detect Snares and Pits (V)          AEC 43',
    'Detect Undead (N)                   12',
    'Devolution (V)                      22',
    'Dimensional Block (T)               43',
    'Dimensional Ward (T)                43',
    'Dimensional Portal (T)       43',
    'Dimension Door (M)                  AEC 60',
    'Dimension Leap (F)                  32',
    'Disappear (T)                       43',
    'Disintegrate (M)                    AEC 60',
    'Dispel Evil (D)                     AEC 34',
    'Dispel Magic (V)                    AEC 43',
    'Dispel Magic (M)                    AEC 60',
    'Dispel Magic (D)                    AEC 34',
    'Dispel Phantasm (I)                 AEC 51',
    'Distort Distance (M)                AEC 60',
    'Divide Body (V)                     22',
    'Divide Mind (V)                     22',
    'Divination (D)                      AEC 34',
    'Divine Weather (D)                  AEC 43',
    'Doppelganger (I)                    AEC 51',
    'Drain Energy (D)                    AEC 38',
    'Dreaming (I)                        33',
    'Dream Travel (I)                    34',
    'Drone (V)                           22',
    'Duo-Dimension (M)                   AEC 61',
    'Dweomerlight (T)                    40',
    'Dweomer of Rage (T)                 AEC 61',
    'Dying Words (N)                     12',
    'Earthquake (D)                      AEC 34',
    'Edibility (V)                       23',
    'Egg of Life (V)                     23',
    'Elemental Cancellation (E)          6',
    'Elemental Gate (E)                  6',
    'Elemental Plane Protection, 10\'r (E)6',
    'Elemental Plane Protection (E)      6',
    'Elemental Portal (E)                6',
    'Elemental Portal, Greater (E)       6',
    'Elemental Wrath (E)                 6',
    'Enchant Arms (D)                    AEC 61',
    'Enlarge (M)                         AEC 61',
    'Entangle (V)                        AEC 43',
    'Erase (M)                           AEC 61',
    'ESP (M)                             AEC 61',
    'Exorcise (D)                        AEC 34',
    'Explosive Growth (V)                23',
    'Explosive Runes (R)                 AEC 62',
    'Extend Duration III (M)             AEC 62',
    'Extend Duration II (M)              AEC 62',
    'Extend Duration I (M)               AEC 62',
    'Exterminate (N)                     12',
    'Extinction (V)                      23',
    'Faerie Fire (M)                     AEC 43',
    'Faithful Hound (T)                  AEC 62',
    'False Gold (M)                      AEC 62',
    'False Trap (M)                      AEC 62',
    'Hideaway (T)                        43',
    'Fear (I)                            AEC 51',
    'Fear (M)                            AEC 62',
    'Feather Fall (M)                    AEC 62',
    'Feeblemind (V)                      AEC 43',
    'Feeblemind (M)                      AEC 63',
    'Feign Death (V)                     AEC 43',
    'Feign Death (M)                     AEC 63',
    'Feign Death (D)                     AEC 35',
    'Figment (I)                         34',
    'Find the Path (D)                   AEC 35',
    'Find Traps (D)                      AEC 35',
    'Finger of Death (M)                 AEC 44',
    'Fireball (M)                        AEC 63',
    'Fire Chariot (M)                    AEC 44',
    'Firelight (E)                       7',
    'Fire Seeds (T)                      AEC 44',
    'Fire Shield (M)                     AEC 63',
    'Fire Trap (R)                       AEC 63',
    'Flame Arrow (M)                     AEC 64',
    'Flame Charm (T)                     AEC 64',
    'Flame Strike (D)                    AEC 35',
    'Flash Fire (E)                      AEC 44',
    'Flesh Blast (V)                     23',
    'Floating Disc (M)                   AEC 64',
    'Fly (M)                             AEC 64',
    'Fog Cloud (I)                       AEC 51',
    'Hand, Forceful (T)                   AEC 64',
    'Freezing Sphere (M)                 AEC 64',
    'Full Codex (T)                      44',
    'Fumble (M)                          AEC 64',
    'Fungal Growth (V)                   23',
    'Gaseous Form (N)                    12',
    'Gate (M)                            AEC 64',
    'Gate (D)                            AEC 35',
    'Geas (M)                            AEC 65',
    'Geas (D)                           AEC 37',
    'Gelatinous Transformation (T)       45',
    'Genesis (V)                         24',
    'Ghoul Touch (N)                     12',
    'Glamour (T)                         38',
    'Glass Like Steel (T)                AEC 65',
    'Globe of Invulnerability, Lesser (T)  AEC 65',
    'Globe of Invulnerability (T)        AEC 65',
    'Glyph of Warding (D)                AEC 35',
    'Grapple (T)                         46',
    'Hand, Grasping (T)                   AEC 65',
    'Grease (T)                          45',
    'Guardian Spirit (N)                 12',
    'Guards and Wards (M)                AEC 65',
    'Gust of Wind (M)                    AEC 66',
    'Hallucinatory Terrain (V)           AEC 44',
    'Hallucinatory Terrain (I)           AEC 51',
    'Hallucinatory Terrain (M)           AEC 66',
    'Hapless Fool (T)                    41',
    'Harm (D)                            AEC 35',
    'Haste (M)                           AEC 66',
    'Haunting (N)                        12',
    'Heal (D)                            AEC 35',
    'Heat Metal (M)                      AEC 44',
    'Hibernate (V)                       24',
    'Hide (T)                            43',
    'Hive Mind (V)                       24',
    'Hive Sight (V)                      24',
    'Hold Animal (V)                     AEC 45',
    'Hold Monster (M)                    AEC 66',
    'Hold Person (M)                     AEC 66',
    'Hold Person (D)                     AEC 35',
    'Hold Portal (M)                     AEC 66',
    'Hold Plant and Fungus (V)           AEC 45',
    'Holy Word (D)                       AEC 36',
    'Hypnotic Pattern (I)                AEC 51',
    'Hypnotism (I)                       AEC 51',
    'Ice Storm (M)                       AEC 66',
    'Identify (M)                        AEC 66',
    'Illusionary Script (R)              AEC 51',
    'Illusory Abode (I)                  34',
    'Illusory Stamina (I)                AEC 51',
    'Immunity to Disease (V)             24',
    'Immunity to Poison (V)              24',
    'Implant Emotion (I)                 AEC 51',
    'Impregnate (V)                      24',
    'Imprisonment (M)                    AEC 67',
    'Incendiary Cloud (M)                AEC 67',
    'Incinerate / Uncinerate (E)         7',
    'Infravision (M)                     AEC 67',
    'Inhabit Figurine (T)                39',
    'Insect Plague (D)                   AEC 36',
    'Insect Swarm (V)                    AEC 45',
    'Instant Memorization (T)          40',
    'Instant Summons (R)                 AEC 67',
    'Inter (N)                           12',
    'Hand, Interposing (T)                AEC 67',
    'Invisibility 10\'r (I)              AEC 52',
    'Invisibility 10\'r (M)              AEC 67',
    'Invisibility to Animals (V)         AEC 45',
    'Invisibility, Greater (I)           AEC 52',
    'Invisibility (I)                    AEC 52',
    'Invisibility, Lesser (T)            38',
    'Invisibility, Limited (F)           32',
    'Invisibility (M)                    AEC 67',
    'Invisible Stalker (M)               AEC 68',
    'Irresistible Dance (M)              AEC 68',
    'Jump (M)                            AEC 68',
    'Knock (M)                           AEC 68',
    'Know Alignment (D)                  AEC 36',
    'Knowledge of Life (N)               13',
    'Lasting Breath (E)                  7',
    'Legend Lore (R)                     AEC 68',
    'Lend Fortitude (N)      13',
    'Levitate (M)                        AEC 68',
    'Lich Touch (N)                      13',
    'Life Cycle (V)                      24',
    'Life Energy Protection (D)          24',
    'Light Codex (T)                     44',
    'Light (I)                           AEC 52',
    'Light (M)                           AEC 68',
    'Lightning Bolt (M)                  AEC 68',
    'Light (D)                           AEC 36',
    'Limited Wish (M)                    AEC 69',
    'Locate Animals (V)                  AEC 45',
    'Locate Object (M)                   AEC 69',
    'Locate Object (D)                   AEC 36',
    'Locate Plants (V)                   AEC 44',
    'Locate Remains (N)                  13',
    'Lost and Found (T)                    41',
#    'Lower Water (M)                     AEC 69',
    'Lower Water (D)                     AEC 36',
    'Magic Aura (M)                      AEC 69',
    'Magic Jar (M)                       AEC 69',
    'Magic Missile (M)                   AEC 69',
    'Magic Mouth (R)                     AEC 70',
    'Magic Sword (M)                     AEC 70',
    'Creation, Major (I)                  AEC 52',
    'Manipulate Fire (E)                 AEC 70',
    'Marionette (T)                      39',
    'Charm Monster, Mass (M)                      AEC 70',
    'Devolution, Mass (V)                 24',
    'Invisibility, Mass (M)               AEC 70',
    'Mutation, Mass (V)                   24',
    'Maze (M)                            AEC 70',
    'Meld Elementals (E)                  7',
    'Memorium (I)                        34',
    'Mending (M)                         AEC 70',
    'Message (M)                         AEC 71',
    'Meteor Swarm (M)                    AEC 71',
    'Mind Blank (M)                      AEC 71',
    'Creation, Minor (I)                  AEC 52',
    'Mirror Image (I)                    AEC 52',
    'Mirror Image (M)                    AEC 71',
    'Misdirection (I)                    AEC 52',
    'Mists of Madness (I)                35',
    'Mnemonic Enhancer (R)               AEC 71',
    'Mnemonic Obfuscation (T)            40',
#    'Move Earth, Lesser (M)              AEC 71',
    'Move Earth (M)                      AEC 71',
    'Mummy Touch (N)                     13',
    'Mutate (V)                          25',
    'Natural Attack, Improved (V)      25',
    'Natural Attack (V)                25',
    'Necrosis (N)                        AEC 37',
    'Neutralize Poison (D)               AEC 36',
    'Nondetection (I)                    AEC 52',
    'Obscuring Mist (V)                  AEC 45',
    'Organ Swap, Greater (N)     13',
    'Organ Swap (N)              13',
    'Pact of Brass (E)                   7',
    'Paralyze (I)                        AEC 52',
    'Parasitic Implantation (V)          25',
    'Part Water (M)                      AEC 72',
    'Part Water (D)                      AEC 36',
    'Passplant (V)                       AEC 46',
    'Invisibility to Undead (N)          14',
    'Passwall (M)                        AEC 72',
    'Pass without Trace (V)              AEC 46',
    'Pathless Land (I)                   35',
    'Permanency (M)                      AEC 72',
    'Phantasmal Door (I)                 AEC 53',
    'Phantasmal Force (I)                AEC 53',
    'Phantasmal Force (M)                AEC 72',
    'Phantasmal Force, Greater (I)       AEC 53',
    'Phantasmal Killer (I)               AEC 53',
    'Phantasmal Monsters I (I)             AEC 53',
    'Phantasmal Monsters II (I)    AEC 53',
    'Phantasmal Monsters III (I)    AEC 53',
    'Phantasm of Forgetting (I)          36',
    'Phantasm of the Laughing Gnome (T)  42',
    'Phase Door (M)                      AEC 72',
    'Plane Shift (D)                     AEC 36',
    'Plant Growth (M)                    AEC 72',
    'Plant Metabolism (V)                25',
    'Plant Symbiosis (V)                 25',
    'Poison (D)                          AEC 36',
    'Polymorph Any Object (M)            AEC 72',
    'Polymorph Others (M)                AEC 73',
    'Polymorph Self (M)                  AEC 73',
    'Polyvorousness (V)                  25',
    'Portent of Doom (N)                 14',
    'Power Word Blind (M)                AEC 73',
    'Power Word Kill (M)                 AEC 73',
    'Power Word Stun (M)                 AEC 73',
    'Prayer (D)                          AEC 37',
    'Pre-emptive Strike (T)              42',
    'Preserve Dead (N)                   14',
    'Prismatic Beam (I)                  36',
    'Prismatic Sphere (M)                AEC 73',
    'Prismatic Spray (I)                 AEC 53',
    'Prismatic Wall (I)                  AEC 54',
    'Produce Flame (M)                   AEC 46',
    'Project Image (I)                   AEC 54',
    'Project Image (M)                   AEC 74',
    'Protection 10\'r (M)                AEC 74',
    'Protection 10\'r (D)                AEC 37',
    'Protection from Element (D)         AEC 46',
    'Protection from Missiles (M)        AEC 74',
    'Protection from Enchantment (D)     AEC 77',
    'Protection from Fear (D)            AEC 38',
    'Protection (M)                      AEC 74',
    'Protection (D)                      AEC 37',
    'Purify Food and Drink (D)           AEC 37',
    'Pyrotechnics (M)                    AEC 74',
    'Raise Dead, Lesser (N)              14',
    'Raise Dead (D)                      AEC 37',
    'Ray of Enfeeblement (M)             AEC 74',
    'Ray of Fire / Cold (E)              8',
    'Ray of Pain (N)                     14',
#    'Read Languages (M)                  AEC 74',
    'Read Magic (E)                      8',
    'Read Magic (I)                      36',
    'Read Magic (M)                      AEC 74',
    'Read Magic (N)                      14',
    'Read Magic (V)                      26',
    'Reassemble (N)                      14',
    'Refraction (I)                      AEC 54',
    'Regenerate (D)                      AEC 37',
    'Regeneration, Extraordinary (V)     23',
    'Regeneration, Greater (V)           26',
    'Regeneration (V)                    26',
    'Regenerative Pupation (V)           26',
    'Reincarnate (V)                     AEC 46',
    'Reincarnate (M)                     AEC 75',
    'Reinstate Spirit (N)                15',
    'Relentless Binding (T)              46',
    'Remove Curse (M)                    AEC 75',
    'Remove Curse (D)                    AEC 38',
    'Repel Vermin (V)                    AEC 47',
    'Repel Wood (V)                      AEC 47',
    'Replicate Lifeform (V)              26',
    'Reptilian Metabolism (V)            26',
    'Repulsion (M)                       AEC 75',
    'Resist Element (D)                     AEC 38',
    'Resist Turning (N)                  15',
    'Restoration (D)                     AEC 38',
    'Resurrection (D)                    AEC 38',
    'Reveal Charm (D)                    AEC 38',
    'Reverse Gravity (M)                 AEC 75',
    'Dispel Shapechange (V)              26',
    'Rope Like Steel (T)                 47',
    'Rope Trick (I)                      AEC 54',
    'Rope Trick (M)                      AEC 75',
    'Rope Walk (T)                       47',
    'Rope Ward (T)                       47',
    'Rotational Acceleration (T)         44',
    'Sacrificial Exchange (N)        15',
    'Sanctuary (D)                       AEC 38',
    'Scare (M)                           AEC 75',
    'Scribe (M)                          AEC 75',
    'Script Codex (T)                    44',
    'Seal Tomb (N)                       15',
    'Seasong / Windsong / Firesong (E)   8',
    'Secret Chest (R)                    AEC 76',
    'Shadow Evocation, Greater (I)       AEC 54',
    'Shadow Evocation (I)                AEC 54',
    'Shadow Touch (N)                    15',
    'Shape Change (M)                    AEC 76',
    'Shapes (E)                          8',
    'Shatter (M)                         AEC 76',
    'Shield (M)                          AEC 76',
    'Shillelagh (D)                      AEC 47',
    'Shocking Grasp (M)                  AEC 76',
    'Silence 15\'r (D)                   AEC 39',
    'Simulacrum (R)                      AEC 76',
    'Skein (T)                           47',
    'Skeletal Army (N)                   15',
    'Skeletal Servitor (N)               15',
    'Skin Transformation (V)             26',
    'Skull Sight (N)                     15',
    'Skull Speech (N)                    15',
    'Slapstick Fun! (T)                  42',
    'Sleep (M)                           AEC 77',
    'Slime Blast (T)                     45',
    'Slow (M)                            AEC 66',
    'Snake Charm (D)                     AEC 39',
    'Snare (V)                           AEC 47',
    'Solid Fog (I)                       36',
    'Sound Codex (T)                     45',
    'Speak with Animals (D)              AEC 39',
    'Speak with Creatures (D)            AEC 39',
    'Speak with Dead (D)                 AEC 39',
    'Speak with Plants (D)               AEC 39',
    'Spectral Force (I)                  AEC 54',
    'Spectral Force, Permanent (I)       AEC 54',
    'Spectral Force, Programmed (I)      AEC 54',
    'Spectral Hand (N)                   16',
    'Spell Door (T)                      44',
    'Spell Reading (T)                   40',
    'Sphere of Annihilation (T)          44',
    'Spider Climb (M)                    AEC 77',
    'Spider Skein (T)                    47',
    'Spiritual Weapon (D)                AEC 39',
    'Spiritwrack (R)                     AEC 77',
    'Spook (T)                           38',
    'Spore Blast (V)                     27',
    'Spore Cloud (V)                     27',
    'Spying Sigil (T)                    41',
    'Statue (M)                          AEC 77',
    'Staunch Blood Flow (V)              27',
    'Steal Life Force (N)                16',
    'Steal Spell (T)                     41',
    'Sticks to Snakes (V)                AEC 47',
    'Sticks to Snakes (D)                AEC 39',
    'Stinking Cloud (M)                  AEC 77',
    'Stone Tell (M)                      AEC 40',
    'Stone to Flesh (M)                  AEC 78',
    'Strengthen Rope (T)                 47',
    'Strength (M)                        AEC 78',
    'Striking (D)                        AEC 40',
    'Stumble (M)                         AEC 47',
    'Suggestion (M)                      AEC 78',
    'Suggestion, Mass (I)                AEC 54',
    'Summon Animal I (V)                 AEC 48',
    'Summon Animal II (V)                AEC 48',
    'Summon Animal III (V)               AEC 48',
    'Summon Demon (R)                    AEC 78',
    'Summon Demon (N)                    16',
    'Summon Dimensional Horror (T)       44',
    'Summon Elemental Horror (E)         8',
    'Summon Elemental I (E)              8',
    'Summon Elemental II (E)             8',
    'Summon Elemental III (E)            8',
    'Summon Elementine, Lesser (E)       8',
    'Summon Familiar (M)                 AEC 78',
    'Summon Familiar (N)                 16',
    'Summon Fey Kin (F)                  32',
    'Summon Elemental Kin (E)    8',
    'Summon Elementine, Greater (E)       9',
    'Summon Monster III (M)              AEC 79',
    'Summon Monster II (M)               AEC 79',
    'Summon Monster I (M)                AEC 79',
    'Summon Monster IV (M)               AEC 79',
    'Summon Monster VII (M)              AEC 79',
    'Summon Monster VI (M)               AEC 79',
    'Summon Monster V (M)                AEC 79',
    'Summon Shadow (I)                   AEC 54',
    'Summon Swarm (N)                    16',
    'Summon Sylvan Beings (V)            AEC 48',
    'Summon Undead III (N)               17',
    'Summon Undead II (N)                16',
    'Summon Undead I (N)                 16',
    'Summon Undead IV (N)                17',
    'Summon Undead VII (N)               17',
    'Summon Undead VI (N)                17',
    'Summon Undead V (N)                 17',
    'Survival of the Fittest (V)         27',
    'Swarm Transformation (N)            17',
    'Symbiotic Familiar (V)              27',
    'Symbol (M)                          AEC 79',
    'Symbol (N)                          17',
    'Symbol (D)                          AEC 40',
    'Telekinesis (M)                     AEC 80',
    'Teleport (F)                        32',
    'Teleport (M)                        AEC 80',
    'Temporal Stasis (M)                 AEC 80',
    'Tessellate (T)                      44',
    'Tidal Force (E)                     9',
    'Time Flow (I)                       36',
    'Time Stop (M)                       AEC 80',
    'Tiny Hut (M)                        AEC 80',
    'Tongues (M)                         AEC 81',
    'Tongues (D)                         AEC 40',
    'Transfer Pregnancy (V)              28',
    'Transformative Pupation (V)         28',
    'Transmute Metal to Wood (T)         AEC 48',
    'Transmute Rock to Mud (E)           AEC 81',
    'Transport via Plants (M)            AEC 48',
    'Trap the Soul (R)                   AEC 81',
    'Tree (V)                            AEC 49',
    'Tree Stride (V)                     AEC 49',
    'Trigger (T)                         41',
    'True Seeing (I)                     AEC 54',
    'True Seeing (D)                     AEC 40',
    'Uncontrollable Laughter (T) 42',
    'Undead Regeneration (N)             17',
    'Undo (T)                            42',
    'Unhallow (D)                        17',
    'Unseen Servant (M)                  AEC 81',
    'Upper Hand (I)                      36',
    'Vacuum (E)                          9',
    'Valour in Death (N)                 17',
    'Vampiric Enslavement (N)            18',
    'Vanish (M)                          AEC 81',
    'Vats of Creation (V)                28',
    'Veil (I)                            AEC 55',
    'Venomous Blood (V)                  28',
    'Venom (V)                           28',
    'Ventriloquism (M)                   AEC 81',
    'Viral Meme (I)                      36',
    'Virus (V)                           28',
    'Vision (I)                          AEC 55',
    'Vitality Surge (V)                  28',
    'Voodoo Doll (T)                     39',
    'Wall of Fire (V)                    AEC 49',
    'Wall of Fire (M)                    AEC 81',
    'Wall of Force (M)                   AEC 81',
    'Wall of Gloom (N)                   18',
    'Wall of Ice (M)                     AEC 81',
    'Wall of Iron (M)                    AEC 81',
    'Wall of Stone (M)                   AEC 82',
    'Wall of Thorns (V)                  AEC 49',
    'Wall of Vapor (I)                   AEC 55',
    'Warp Wood (V)                       AEC 49',
    'Water Breathing (M)                 AEC 82',
    'Web (M)                             AEC 82',
    'Web of Arachne (T)                  47',
    'Web Walk (T)                        47',
    'Weird (I)                           36',
    'Wind Walk (D)                       AEC 40',
    'Wish (M)                            AEC 82',
    'Wizard Eye (M)                      AEC 56',
    'Wizard Lock (M)                     AEC 56',
    'Word of Recall (D)                  AEC 40',
    'Xenogamy (V)                        29',
    'Yeast Growth (V)                    29',
    'Zoetrope (T)                        42',
    'Zombie Servitor (N)                 18',
    'Zone of Creeping Terror (N)         18',
    'Zone of Death (N)                   18',
    'Zone of Sinister Stillness (N)      18',
    'Zone of Weakness (N)                18',
    '''Baltron's Effusive Bloodboil (T)  BM''',
    '''Djriixim's Purple Haze (T)        BM''',
    '''Fennril's Exquisite Strangulation (T)  BM''',
    '''Galaxina's Scintillating Spark Shower (T)  BM''',
    '''Hitzemun's Blue Feet (T)          BM''',
    '''Mazakala's Mucilaginous Effluvium (T)  BM''',
    '''Zozomir's Stentorian Shout (T)    BM''',
    'Spiritual Armor (D)                 BM',
    'Ice Bolt (E)                        GG',
    'Fire Storm (E)                      GG',
    'Crystal Bolt (E)                    GG',
    'Create Water (E)                    GG',
    'Lucid Discovery (I)                 GG',
    'Control Illumination (I)          GG',
    'Shape Vegetable (M)                 GG',
    'Shape Mineral (M)                   AEC 78',
    'Shape Metal (M)                     GG',
    'Wall of Bone (N)                    GG',
    'Skull Animation (N)                 GG',
    'Shape Animal (V)                    GG',
    'Hive Control (V)                    GG',
    'Embue Element (E)                   GG',
    'Elemental Darts (E)                 GG',
#    'Nature I (W)                        GG',
#    'Nature II (W)                       GG',
#    'Nature III (W)                      GG',
#    'Red Ward (W)                        GG',
#    'Blue Ward (W)                       GG',
#    'Elemental Darts (W)                 GG',
#    'Boon (W)                            GG',
#    'Bane (W)                            GG',
#    'Detect (W)                          GG',
#    'Duplicate (W)                       GG',
#    'Meta Magic (W)                      GG',
#    'Mind\'s Eye (W)                     GG',
#    'Air & Water (W)                     GG',
#    'Cure, Minor (W)                     GG',
#    'Cure, Major (W)                     GG',
    'Symbiotic Familiar (R)              GG',
    'Summon Familiar (R)                 GG',
    'Detect Magic (R)                    GG',
    'Ritual Curse (R)                    GG',
    'Summon Weather (R)                 GG',
    ]

lists = {
    'mage': [
        ['Burning Hands', 'Charm Person', 'Read Languages', 'Feather Fall', 'Floating Disc', 'Hold Portal', 'Jump', 'Light', 'Magic Missile', 'Shield', 'Shocking Grasp', 'Sleep'],
        ['Summon Monster I', 'Wizard Lock', 'Blink', 'Hold Person', 'Invisibility', 'Knock', 'Levitate', 'Locate Object', 'Mirror Image', 'Stinking Cloud', 'Strength', 'Web'],
        ['Summon Monster II', 'Wizard Eye', 'Continual Light', 'Dispel Magic', 'Fireball', 'Fly', 'Hold Monster', 'Haste', 'Infravision (M)', 'Lightning Bolt', 'Tongues', 'Water Breathing'],
        ['Summon Monster III', 'Charm Monster', 'Confusion', 'Dimension Door', 'Fear', 'Magic Sword', 'Power Word Stun', 'Passwall', 'Ice Storm', 'Reverse Gravity', 'Polymorph Others', 'Wall of Fire'],
        ['Summon Monster IV', 'Antipathy/Sympathy', 'Cloudkill', 'Duo-Dimension', 'Feeblemind', 'Fireball, Greater', 'Maze', 'Stone Tell', 'Telekinesis', 'Teleport', 'Wall of Force', 'Project Image'],
        ['Summon Monster V', 'Polymorph Self', 'Death', 'Disintegrate', 'Gate', 'Geas', 'Irresistible Dance', 'Invisible Stalker', 'Mind Blank', 'Power Word Blind', 'Repulsion', 'Wall of Iron'],
        ['Summon Monster VI', 'Charm Monster, Mass', 'Phase Door', 'Symbol'],
        ['Summon Monster VII', 'Polymorph Any Object', 'Power Word Kill', 'Meteor Swarm'],
        ['Prismatic Sphere', 'Shape Change', 'Temporal Stasis', 'Time Stop'],
        ],
    'elementalist': [
        ['Elemental Darts (E)', 'Pyrotechnics (M)', 'Burning Hands (M)', 'Create Water', 'Feather Fall (M)', 'Firelight', 'Lasting Breath', 'Ray of Fire / Cold', 'Resist Element (D)', 'Seasong / Windsong / Firesong', 'Summon Elementine, Lesser', 'Wall of Vapor (I)'],
        ['Continual Light (M)', 'Embue Element', 'Flash Fire', 'Elemental Cancellation', 'Flame Arrow (M)', 'Fog Cloud (I)', 'Heat Metal (M)', 'Incinerate / Uncinerate', 'Shape Mineral (M)', 'Summon Elementine, Greater', 'Tidal Force', 'Tiny Hut (M)'],
        ['Transmute Rock to Mud', 'Crystal Bolt', 'Ice Bolt', 'Fireball (M)', 'Fly (M)', 'Gust of Wind (M)', 'Protection from Element (D)', 'Summon Elemental I', 'Stone Tell', 'Control Temperature (D)', 'Atmosphere Bubble (M)', 'Vacuum'],
        ['Contact Elemental Spirit', 'Animate Mineral (M)', 'Fire Shield (M)', 'Fire Storm', 'Ice Storm (M)', 'Part Water (M)', 'Move Earth (M)', 'Summon Elemental II', 'Summon Elemental Horror', 'Wall of Fire (M)', 'Wall of Ice (M)', 'Wind Walk (D)'],
        ['Command Elemental I', 'Cloudkill (M)', 'Freezing Sphere (M)', 'Cone of Cold (M)', 'Cone of Heat (M)', 'Control Winds (D)', 'Elemental Plane Protection', 'Passwall (M)', 'Summon Elemental III', 'Wall of Stone (M)', 'Fire Chariot (M)', 'Statue (M)'],
        ['Command Elemental II', 'Amalgam of Earth and Air', 'Amalgam of Fire and Water', 'Aerial Servant (D)', 'Conflagration (M)', 'Fireball, Greater (M)', 'Disintegrate (M)', 'Elemental Gate', 'Summon Elemental Kin'],
        ['Command Elemental III', 'Earthquake (D)', 'Meld Elementals'],
        ['Elemental Portal', 'Incendiary Cloud (M)', 'Meteor Swarm (M)'],
        ['Brimstone Monolith', 'Elemental Wrath', 'Imprisonment (M)', 'Pact of Brass'],
        ],
    'illusionist': [
        ['Phantasmal Force', 'Auditory Illusion', 'Blur', 'Color Spray', 'Darkness (M)', 'Detect Illusion', 'Detect Invisible', 'Hypnotism', 'Light (M)', 'Refraction', 'Wall of Vapor', 'Ventriloquism (M)'],
        ['Phantasmal Force, Greater', 'Conjure Animals (D)', 'Blindness / Deafness', 'Charm Person', 'Fog Cloud', 'Hold Monster (M)', 'Hypnotic Pattern', 'Invisibility', 'Phantasmal Door', 'Mirror Image', 'Misdirection', 'Rope Trick'],
        ['Spectral Force', 'Phantasmal Killer', 'Control Illumination', 'Confusion', 'Dispel Phantasm', 'Illusory Stamina', 'Fear', 'Creation, Minor', 'Invisibility 10\'r', 'Nondetection', 'Paralyze', 'Suggestion (M)'],
        ['Phantasmal Monsters I', 'Spectral Force, Programmed', 'Charm Monster', 'Confusion, Greater', 'Maze (M)', 'Invisibility, Greater', 'Creation, Major', 'Solid Fog', 'True Seeing', 'Protection from Missiles (M)', 'Project Image', 'Veil'],
        ['Phantasmal Monsters II', 'Teleport (M)', 'Invisible Stalker (M)', 'Feeblemind (M)', 'Finger of Death (M)', 'Gaseous Form (N)', 'Mind Blank (M)', 'Shadow Evocation', 'Suggestion, Mass', 'Summon Shadow', 'Time Flow', 'Memorium'],
        ['Phantasmal Monsters III', 'Dreaming', 'Irresistible Dance', 'Spectral Force, Permanent', 'Shadow Evocation, Greater', 'Prismatic Beam', 'Upper Hand', 'Vision'],
        ['Dream Travel', 'Phantasm of Forgetting', 'Prismatic Spray'],
        ['Figment', 'Illusory Abode', 'Pathless Land', 'Prismatic Wall'],
        ['Alter Reality', 'Mists of Madness', 'Viral Meme', 'Weird'],
        ],
    'necromancer': [
        ['Command Dead', 'Command Undead', 'Darkness (M)', 'Dying Words', 'Locate Remains', 'Invisibility to Undead', 'Preserve Dead', 'Ray of Enfeeblement (M)', 'Scare (M)', 'Spectral Hand', 'Shadow Touch', 'Skeletal Servitor'],
        ['Summon Undead I', 'Choke', 'Corpse Visage', 'Death Recall', 'Feign Death (M)', 'Ghoul Touch', 'Ray of Pain', 'Resist Turning', 'Seal Tomb', 'Speak with Dead (D)', 'Summon Swarm', 'Zombie Servitor'],
        ['Summon Undead II', 'Infravision (M)', 'Animate Dead (D)', 'Lich Touch', 'Fear (M)', 'Reassemble', 'Hold Person (M)', 'Skull Sight', 'Skull Speech', 'Valour in Death', 'Vampiric Enslavement', 'Zone of Sinister Stillness'],
        ['Summon Undead III', 'Slow (M)', 'Curse (D)', 'Wall of Gloom', 'Charm Undead', 'Detach', 'Inter', 'Mummy Touch', 'Raise Dead, Lesser', 'Sacrificial Exchange', 'Swarm Transformation', 'Zone of Weakness'],
        ['Summon Undead IV', 'Skull Animation', 'Curse of Undeath', 'Contact Spirit', 'Wall of Bone', 'Death (M)', 'Gaseous Form', 'Guardian Spirit', 'Magic Jar (M)', 'Portent of Doom', 'Summon Shadow (I)', 'Zone of Creeping Terror'],
        ['Summon Undead V', 'Bind Spirit', 'Power Word Blind (M)', 'Knowledge of Life', 'Necrosis', 'Organ Swap', 'Undead Regeneration', 'Zone of Death'],
        ['Summon Undead VI', 'Death Geas', 'Destruction', 'Gate'],
        ['Summon Undead VII', 'Organ Swap, Greater', 'Power Word Kill', 'Symbol'],
        ['Raise Dead (D)', 'Reinstate Spirit', 'Steal Life Force', 'Skeletal Army'],
        ],
    'vivimancer': [
        ['Detect Poison', 'Edibility', 'Entangle', 'Jump (M)', 'Natural Attack', 'Invisibility to Undead', 'Skin Transformation', 'Sleep (M)', 'Speak with Animals (D)', 'Spider Climb (M)', 'Spore Cloud', 'Vitality Surge'],
        ['Hyper Healing', 'Hyper Immune System', 'Hyper Metabolism', 'Drone', 'Fungal Growth', 'Hold Animal', 'Infravision (M)', 'Summon Swarm (N)', 'Staunch Blood Flow', 'Water Breathing (M)', 'Warp Wood', 'Web (M)'],
        ['Chimera I', 'Animal Growth', 'Cause Disease (D)', 'Cannibalize', 'Divide Body', 'Fly (M)', 'Hold Plant and Fungus', 'Immunity to Disease', 'Regeneration', 'Repel Wood', 'Wall of Thorns', 'Water Breathing (M)'],
        ['Chimera II', 'Explosive Growth', 'Hive Mind', 'Immunity to Poison', 'Regeneration, Greater', 'Regenerative Pupation', 'Life Cycle', 'Plant Symbiosis', 'Plant Growth (M)', 'Polymorph Self (M)', 'Speak with Plants (D)', 'Spore Blast'],
        ['Summon Animal I', 'Chimera III', 'Commune with Nature', 'Anti-plant Ward', 'Charm Plants (M)', 'Clone (M)', 'Regeneration, Extraordinary', 'Devolution', 'Divide Mind', 'Insect Plague (D)', 'Venomous Blood', 'Shape Animal'],
        ['Summon Animal II', 'Anti-animal Ward', 'Creeping Doom', 'Egg of Life', 'Mutate', 'Hive Control', 'Flesh Blast', 'Parasitic Implantation', 'Transfer Pregnancy', 'Reincarnate (M)', 'Transformative Pupation', 'Virus'],
        ['Summon Animal III', 'Impregnate', 'Genesis', 'Xenogamy'],
        ['Devolution, Mass', 'Shape Change (M)', 'Survival of the Fittest', 'Vats of Creation'],
        ['Artificial Intelligence', 'Extinction', 'Mutation, Mass', 'Temporal Stasis (M)'],
        ],

#    'red': [
#        ['Red Ward', 'Elemental Darts', 'Burning Hands (M)', 'Firelight (E)', 'Hold Portal (M)', 'Ray of Fire / Cold (E)'],
#        ['Summon Monster I (M)', 'Heat Metal (M)', 'Knock (M)', 'Shatter (M)', 'Striking (D)', 'Strength (M)'],
#        ['Summon Monster II (M)', 'Crystal Bolt (E)', 'Fireball', 'Haste', 'Enchant Arms (D)', 'Shape Mineral (M)'],
#        ['Summon Monster III (M)', 'Animate Mineral (M)', 'Fire Shield (M)', 'Fire Storm (E)', 'Move Earth (M)', 'Wall of Fire (M)'],
#        ['Summon Monster IV (M)', 'Fireball, Greater (M)', 'Summon Elemental II (E)', 'Flame Strike (D)', 'Stone Tell (M)', 'Wall of Stone (M)'],
#        ],
#    'green': [
#        ['Nature I', 'Summon Monster I (M)', 'Jump (M)', 'Entangle (V)', 'Charm Animal (V)', 'Cure, Minor'],
#        ['Nature II', 'Summon Monster II (M)', 'Enlarge (M)', 'Barkskin (V)', 'Web (M)', 'Stumble (M)'],
#        ['Nature III', 'Summon Monster III (M)', 'Summon Animal I (V)', 'Anti-Magic Ward (M)', 'Tiny Hut (M)', 'Wall of Thorns (V)'],
#        ['Summon Monster IV (M)', 'Summon Animal II (V)', 'Charm Plants (M)', 'Commune with Nature (V)', 'Dispel Evil (D)', 'Plant Symbiosis (V)'],
#        ['Summon Monster V (M)', 'Summon Animal III (V)', 'Antipathy/Sympathy', 'Cloudkill (M)', 'Control Weather, Greater (D)', 'Anti-Animal Ward (V)'],
#        ],
#    'blue': [
#        ['Blue Ward', 'Meta Magic', 'Shield', 'Unseen Servant', 'Feather Fall', 'Hypnotism'],
#        ['Blur', 'Invisibility', 'Air & Water (W)', 'Mind\'s Eye', 'Stinking Cloud', 'Hold Monster (M)'],
#        ['Anti-Magic Ward (M)', 'Duplicate (W)', 'Creation, Minor (I)', 'Lightning Bolt (M)', 'Protection from Missiles (M)', 'True Seeing (I)'],
#        ['Charm Monster (M)', 'Confusion (M)', 'Phantasmal Monsters I (I)', 'Implant Emotion (I)', 'Polymorph Others (M)', 'Wall of Ice (M)'],
#        ['Repulsion (M)', 'Shadow Evocation (I)', 'Feeblemind (M)', 'Summon Elemental II (E)', 'Teleport (M)', 'Time Flow (I)'],
#        ],
#    'white': [
#        ['Cure, Minor',  'Protection (D)', 'Command (D)', 'Light (D)', 'Allure (M)', 'Sanctuary (D)'],
#        ['Boon', 'Detect', 'Spiritual Weapon (D)', 'Silence 15\'r (D)', 'Knock (M)', 'Lend Fortitude (N)'],
#        ['Cure, Major',  'Protection 10\'r (D)', 'Continual Light (D)', 'Glyph of Warding (D)', 'Enchant Arms (D)', 'Immunity to Disease (V)'],
#        ['Regenerate (D)', 'Dispel Evil (D)', 'Divination (D)', 'Magic Sword (M)', 'True Seeing (D)', 'Immunity to Poison (V)'],
#        ['Heal (D)', 'Commune (D)', 'Word of Recall (D)', 'Blade Barrier (D)', 'Raise Dead (D)', 'Wall of Stone (M)'],
#        ],
#    'black': [
#        ['Shadow Touch (N)', 'Protection (D)', 'Command (D)', 'Darkness (M)', 'Charm Person (M)', 'Spider Climb (M)'],
#        ['Bane', 'Detect', 'Spiritual Weapon (D)', 'Silence 15\'r (D)', 'Fog Cloud (I)', 'Hold Person (D)'],
#        ['Cause Disease (D)', 'Poison', 'Protection 10\'r (D)', 'Continual Darkness (D)', 'Animate Dead (D)', 'Suggestion (M)'],
#        ['Dispel Evil (D)', 'Fear (M)', 'Charm Undead (N)', 'Paralyze (I)', 'Wall of Gloom (N)', 'Mummy Touch (N)'],
#        ['Harm (D)', 'Commune (D)', 'Summon Shadow (I)', 'Feeblemind (M)', 'Magic Jar (M)', 'Wall of Bone (N)'],
#        ],


##    [
##    'Augury (D)',
##    'Bless (D)',
##    'Call Lightning (D)',
##    'Command (D)',
##    'Darkness (D)',
##    'Delay Poison (D)',
##    'Detect Evil (D)',
##    'Divine Weather (D)',
##    'Find Traps (D)',
##    'Life Energy Protection (D)',
##    'Light (D)',
##    'Protection (D)',
##    'Protection from Fear (D)',
##    'Purify Food and Drink (D)',
##    'Resist Element (D)',
##    'Sanctuary (D)',
##    'Snake Charm (D)',
##    'Spiritual Weapon (D)',
##    ]
#, 'Hold Person (M)'
#    'overlord': [
#        ['Command Dead', 'Dying Words', 'Locate Remains', 'Invisibility to Undead', 'Preserve Dead', 'Ray of Enfeeblement (M)'],
#
#        ['Summon Monster I', 'Choke', 'Corpse Visage', 'Death Recall', 'Feign Death (M)', 'Ray of Pain', 'Seal Tomb'],
#        ['Summon Monster II', 'Fear (M)', 'Valour in Death', 'Zone of Sinister Stillness'],
#        ['Summon Monster III', 'Wall of Gloom', 'Charm Undead', 'Detach', 'Inter', 'Mummy Touch', 'Raise Dead, Lesser', 'Sacrificial Exchange', 'Swarm Transformation', 'Zone of Weakness'],
#        ['Summon Monster IV', 'Skull Animation', 'Curse of Undeath', 'Contact Spirit', 'Wall of Bone', 'Death (M)', 'Gaseous Form', 'Guardian Spirit', 'Magic Jar (M)', 'Portent of Doom', 'Summon Shadow (I)', 'Zone of Creeping Terror'],
#        ['Summon Monster V', 'Bind Spirit', 'Power Word Blind (M)', 'Knowledge of Life', 'Necrosis (N)', 'Organ Swap', 'Undead Regeneration', 'Zone of Death'],
#        ],
    }
